// app/src/connections/connection-detail/connection-detail.component.ts
import { Component, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'connection-detail',
  templateUrl: './connection-detail.component.html',
  styleUrls: ['./connection-detail.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class ConnectionDetailsComponent {
  options: any = ['Select', 'Option1', 'Option2', 'Option3'];
}

<div class="connection-detail">
  <div class="headerContainer">
    <div class="left-elements">
      <div class="left-child">
        <div class="back-circle">
          <div
            class="circle"
            [routerLink]="['/connections/list']"
            routerLinkActive="router-link-active">
            <mat-icon class="back" svgIcon="back">arrow_back</mat-icon>
          </div>
        </div>
      </div>
      <div class="right-child">
        <div class="bread-crum">Connections / <span>View Connection</span></div>
        <div class="template-label">Connection Details</div>
      </div>
    </div>

    <div class="right-elements">
      <button
        class="theme-button active-btn"
        mat-flat-button
        aria-label="Edit Template"
        routerLinkActive="button-active"
        routerLink="/connections/create">
        <mat-icon svgIcon="edit-white"></mat-icon>Edit
      </button>
    </div>
  </div>
  <div class="childContainer">
    <div class="inner-headerContainer">
      <div class="left-elements">
        <div class="right-child">
          <div class="temp-properties-name">Connection Details</div>
        </div>
      </div>
    </div>
    <div class="main-container bottom-radius-none">
      <div class="full-width">
        <div class="one-line">
          <div class="left-box">
            <div class="input-container">
              <div class="label-container">
                <label class="input-label">Connection Name *</label>
              </div>
              <label class="input-value">Connection 123</label>
            </div>
          </div>
          <div class="middle-box">
            <div class="input-container">
              <div class="label-container">
                <label class="input-label">Partner *</label>
              </div>
              <label class="input-value">Hertz</label>
            </div>
          </div>
        </div>
        <div class="one-line">
          <div class="one-third-box">
            <div class="input-container">
              <div class="label-container">
                <label class="input-label">Description *</label>
              </div>
              <label class="input-value"
                >This is an example description that is exceptionally long and
                keeps going no matter what you keep typing</label
              >
            </div>
          </div>
        </div>
        <div class="one-line">
          <div class="left-box">
            <div class="input-container">
              <div class="label-container">
                <label class="input-label">Connection Type *</label>
              </div>
              <label class="input-value">AWS S3</label>
            </div>
          </div>
          <div class="one-third-box">
            <div class="input-container">
              <div class="label-container">
                <label class="input-label">URL *</label>
              </div>
              <label class="input-value">s3://abc.com</label>
            </div>
          </div>
        </div>
        <div class="one-line">
          <div class="left-box">
            <div class="input-container">
              <div class="label-container">
                <label class="input-label">Access Key ID *</label>
              </div>
              <label class="input-value">ASIA25ZZONFD2DMRGH5Z</label>
            </div>
          </div>
          <div class="one-third-box">
            <div class="input-container">
              <div class="label-container">
                <label class="input-label">Secret Access Key *</label>
              </div>
              <label class="input-value"
                >twTeMQsc6EXSw/qM9wafUTRM7bJDpusLCYtH8G3H</label
              >
            </div>
          </div>
        </div>
        <div class="one-line">
          <div class="left-box">
            <div class="input-container">
              <div class="label-container">
                <label class="input-label">Region *</label>
              </div>
              <label class="input-value">Example Region here</label>
            </div>
          </div>
        </div>
        <div class="encry-wrap">
          <div class="connection-aws-title">
            <mat-icon svgIcon="lock"></mat-icon>Encryption
          </div>
          <div class="one-line">
            <div class="left-box">
              <div class="input-container">
                <div class="label-container">
                  <label class="input-label">Encryption Algorithm *</label>
                </div>
                <label class="input-value">Algorithm123</label>
              </div>
            </div>
            <div class="one-third-box">
              <div class="input-container">
                <div class="label-container">
                  <label class="input-label">Encryption Key *</label>
                </div>
                <label class="input-value">file123</label>
              </div>
            </div>
          </div>
          <div class="connection-aws-title">
            <mat-icon svgIcon="compress"></mat-icon>Compression
          </div>
          <div class="one-line">
            <div class="left-box">
              <div class="input-container">
                <div class="label-container">
                  <label class="input-label">Compression Algorithm *</label>
                </div>
                <label class="input-value">Algorithm123</label>
              </div>
            </div>
            <div class="one-third-box">
              <div class="input-container">
                <div class="label-container">
                  <label class="input-label">Compression Level *</label>
                </div>
                <label class="input-value">3</label>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <app-delete-button></app-delete-button>
  </div>
</div>

// app/src/pages/connections/ConnectionDetail.tsx
import React from 'react';
import { 
  Typography, 
  IconButton, 
  Button,
  Card,
  CardContent,
  Grid
} from '@mui/material';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import EditIcon from '@mui/icons-material/Edit';
import { Link } from 'react-router-dom';
import { DeleteButton } from '../../components/common';

const ConnectionDetail: React.FC = () => {
  // In a real implementation, this data would come from props or a data fetching hook
  const data = {
    name: 'Connection 123',
    partner: { name: 'Hertz' },
    connectionType: 'AWS S3',
    url: 's3://abc.com',
    accessKeyId: 'ASIA25ZZONFD2DMRGH5Z',
    secretAccessKey: 'twTeMQsc6EXSw/qM9wafUTRM7bJDpusLCYtH8G3H',
    region: 'Example Region here',
    encryptionAlgorithm: 'Algorithm123',
    encryptionKey: 'file123',
    compressionAlgorithm: 'Algorithm123',
    compressionLevel: '3'
  };

  return (
    <div className="bg-white">
      {/* Header */}
      <div className="flex justify-between items-center px-7 py-4 border-b border-gray-200">
        <div className="flex items-center">
          <div className="mr-4">
            <IconButton 
              component={Link} 
              to="/connections/list"
              className="border border-gray-200 rounded-full"
            >
              <ArrowBackIcon />
            </IconButton>
          </div>
          <div>
            <Typography variant="body2" className="text-gray-700">
              Connections / <span className="text-gray-500">View Connection</span>
            </Typography>
            <Typography variant="h6" className="font-semibold">
              Connection Details
            </Typography>
          </div>
        </div>
        
        <Button
          variant="contained"
          startIcon={<EditIcon />}
          component={Link}
          to="/connections/create"
          className="bg-blue-800 hover:bg-blue-900"
        >
          Edit
        </Button>
      </div>
      
      {/* Main Content */}
      <div className="p-6">
        <div className="border border-gray-200 rounded-t-lg">
          <div className="flex items-center px-5 py-6 border-b border-gray-200">
            <Typography variant="h6" className="font-semibold">
              Connection Details
            </Typography>
          </div>
          
          <Card className="rounded-none shadow-none">
            <CardContent>
              <Grid container spacing={3}>
                {/* Row 1 */}
                <Grid item xs={4}>
                  <div className="px-5 pt-5">
                    <Typography variant="subtitle2" className="text-gray-600 mb-1">
                      Connection Name *
                    </Typography>
                    <Typography variant="body1" className="font-medium text-gray-900">
                      {data.name}
                    </Typography>
                  </div>
                </Grid>
                <Grid item xs={4}>
                  <div className="px-5 pt-5">
                    <Typography variant="subtitle2" className="text-gray-600 mb-1">
                      Partner *
                    </Typography>
                    <Typography variant="body1" className="font-medium text-gray-900">
                      {data.partner.name}
                    </Typography>
                  </div>
                </Grid>
                <Grid item xs={4}></Grid>
                
                {/* Row 2 */}
                <Grid item xs={8}>
                  <div className="px-5 pt-5">
                    <Typography variant="subtitle2" className="text-gray-600 mb-1">
                      Description *
                    </Typography>
                    <Typography variant="body1" className="font-medium text-gray-900">
                      This is an example description that is exceptionally long and keeps going no matter what you keep typing
                    </Typography>
                  </div>
                </Grid>
                <Grid item xs={4}></Grid>
                
                {/* Row 3 */}
                <Grid item xs={4}>
                  <div className="px-5 pt-5">
                    <Typography variant="subtitle2" className="text-gray-600 mb-1">
                      Connection Type *
                    </Typography>
                    <Typography variant="body1" className="font-medium text-gray-900">
                      {data.connectionType}
                    </Typography>
                  </div>
                </Grid>
                <Grid item xs={8}>
                  <div className="px-5 pt-5">
                    <Typography variant="subtitle2" className="text-gray-600 mb-1">
                      URL *
                    </Typography>
                    <Typography variant="body1" className="font-medium text-gray-900">
                      {data.url}
                    </Typography>
                  </div>
                </Grid>
                
                {/* Row 4 */}
                <Grid item xs={4}>
                  <div className="px-5 pt-5">
                    <Typography variant="subtitle2" className="text-gray-600 mb-1">
                      Access Key ID *
                    </Typography>
                    <Typography variant="body1" className="font-medium text-gray-900">
                      {data.accessKeyId}
                    </Typography>
                  </div>
                </Grid>
                <Grid item xs={8}>
                  <div className="px-5 pt-5">
                    <Typography variant="subtitle2" className="text-gray-600 mb-1">
                      Secret Access Key *
                    </Typography>
                    <Typography variant="body1" className="font-medium text-gray-900">
                      {data.secretAccessKey}
                    </Typography>
                  </div>
                </Grid>
                
                {/* Row 5 */}
                <Grid item xs={4}>
                  <div className="px-5 pt-5">
                    <Typography variant="subtitle2" className="text-gray-600 mb-1">
                      Region *
                    </Typography>
                    <Typography variant="body1" className="font-medium text-gray-900">
                      {data.region}
                    </Typography>
                  </div>
                </Grid>
                <Grid item xs={8}></Grid>
                
                {/* Encryption Section */}
                <Grid item xs={12}>
                  <div className="px-5 pt-8 border-t border-gray-200 mt-4">
                    <div className="flex items-center mb-4">
                      <span className="material-icons mr-1">lock</span>
                      <Typography variant="h6" className="font-semibold">
                        Encryption
                      </Typography>
                    </div>
                  </div>
                </Grid>
                
                <Grid item xs={4}>
                  <div className="px-5">
                    <Typography variant="subtitle2" className="text-gray-600 mb-1">
                      Encryption Algorithm *
                    </Typography>
                    <Typography variant="body1" className="font-medium text-gray-900">
                      {data.encryptionAlgorithm}
                    </Typography>
                  </div>
                </Grid>
                <Grid item xs={8}>
                  <div className="px-5">
                    <Typography variant="subtitle2" className="text-gray-600 mb-1">
                      Encryption Key *
                    </Typography>
                    <Typography variant="body1" className="font-medium text-gray-900">
                      {data.encryptionKey}
                    </Typography>
                  </div>
                </Grid>
                
                {/* Compression Section */}
                <Grid item xs={12}>
                  <div className="px-5 pt-8 border-t border-gray-200 mt-4">
                    <div className="flex items-center mb-4">
                      <span className="material-icons mr-1">compress</span>
                      <Typography variant="h6" className="font-semibold">
                        Compression
                      </Typography>
                    </div>
                  </div>
                </Grid>
                
                <Grid item xs={4}>
                  <div className="px-5">
                    <Typography variant="subtitle2" className="text-gray-600 mb-1">
                      Compression Algorithm *
                    </Typography>
                    <Typography variant="body1" className="font-medium text-gray-900">
                      {data.compressionAlgorithm}
                    </Typography>
                  </div>
                </Grid>
                <Grid item xs={8}>
                  <div className="px-5 pb-5">
                    <Typography variant="subtitle2" className="text-gray-600 mb-1">
                      Compression Level *
                    </Typography>
                    <Typography variant="body1" className="font-medium text-gray-900">
                      {data.compressionLevel}
                    </Typography>
                  </div>
                </Grid>
              </Grid>
            </CardContent>
          </Card>
        </div>
        
        {/* Delete Button */}
        <div className="mt-4">
          <DeleteButton>Delete Connection</DeleteButton>
        </div>
      </div>
    </div>
  );
};

export default ConnectionDetail;
