// app/src/pages/Templates/TemplateGridComponent.tsx
// TemplateGridComponent.tsx
import React, { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { useUiConfig } from '@/services/ui-config/useUiConfig';
import DynamicGrid from './DynamicGrid';
import './TemplateGridComponent.css';

interface TemplateGridComponentProps {
  data: any;
  handler: any;
}

const TemplateGridComponent: React.FC<TemplateGridComponentProps> = ({
  data,
  handler,
}) => {
  const { uiConfig, isLoading } = useUiConfig();
  const { register, handleSubmit } = useForm();
  const [config, setConfig] = useState({});

  useEffect(() => {
    const getConfig = async () => {
      const gridViewConfig = await uiConfig.getGridViewConfig('templates');
      setConfig(gridViewConfig || {});
    };
    getConfig();
  }, [uiConfig]);

  const getValue = (value: any) => {
    // implement dateTimeFormat pipe equivalent
    return new Date(value).toLocaleString();
  };

  const copy = (row: any) => {
    handler.copy(row);
  };

  const edit = (row: any) => {
    handler.edit(row);
  };

  const deleteRow = (row: any) => {
    handler.delete(row);
  };

  const openPopup = () => {
    // implement popup dialog equivalent
  };

  if (!config) return null;

  return (
    <div>
      <DynamicGrid
        config={config}
        data={data}
        handler={{
          copy,
          edit,
          delete: deleteRow,
          openPopup,
        }}
      />
    </div>
  );
};

export default TemplateGridComponent;

// app/src/templates/template-grid/template-grid.component.ts
import { Component, Input, ViewChild } from '@angular/core';
import { MatPaginator } from '@angular/material/paginator';
import { DynamicPipeService } from 'src/app/shared/services/dynamic-pipe.service';
import { UiConfigService } from 'src/app/shared/services/ui-config.service';

@Component({
  selector: 'app-template-grid',
  templateUrl: './template-grid.component.html',
  styleUrls: ['./template-grid.component.scss'],
})
export class TemplateGridComponent {
  dataSource: any = [];
  config: any;
  @Input() data;
  @Input() handler: any;
  @ViewChild(MatPaginator) paginator: MatPaginator;
  constructor(
    private pipeService: DynamicPipeService,
    private uiConfigService: UiConfigService,
  ) {}

  async ngOnInit() {
    this.config =
      (await this.uiConfigService.getGridViewConfig('templates')) || {};
  }

  ngOnChanges() {
    if(this.data?.length) {
      this.data.paginator = this.paginator;
    }
  }

  ngAfterViewInit() {
    if (this.data) {
      this.data.paginator = this.paginator;
    }
  }

  getValue(value) {
    return this.pipeService.pipes['dateTimeFormat'](value);
  }

  copy(row: any) {
    this.handler.copy(row);
  }

  edit(row: any): void {
    this.handler.edit(row);
  }

  delete(row: any): void {
    this.handler.delete(row);
  }

  public openPopup(): void {
    //this.dialog.open(popupDialogComponent);
  }
}
