// app/partner/create-partner/create-partner.component.ts
import { Location } from '@angular/common';
import { Component, ViewEncapsulation } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';
import { ActivatedRoute, Router } from '@angular/router';
import { Observable, Subscription, firstValueFrom } from 'rxjs';
import { ConfirmationDialog } from 'src/app/common-components/delete-button/confirmation-dialog.component';
import { UtilsService } from 'src/app/shared/services/utils.service';
import { Partner } from '../../models/partner';
import { sharedConstants } from '../../shared';
import { AlertService } from '../../shared/services/alert.service';
import { PartnersService } from '../../shared/services/partners.service';
import { UiConfigService } from '../../shared/services/ui-config.service';
import { ProgramsService } from './../../shared/services/programs.service';

export interface ICountryAndCode {
  code: string;
  name: string;
}
@Component({
  selector: 'app-create-partner',
  templateUrl: './create-partner.component.html',
  styleUrls: ['./create-partner.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class CreatePartnerComponent {
  formGroup: FormGroup = new FormGroup([]);
  data: any;
  routeSub: Subscription;
  isEdit = false;
  partnerAction: any;
  enumData: any = {};
  program = [];
  config: any;
  isModified: any;
  timeZoneOptions: any;
  partnerTypeOptions: any;
  sub: Subscription;
  partnerId: any;
  deletePermission: boolean;

  constructor(
    private partnersService: PartnersService,
    private alertService: AlertService,
    private router: Router,
    private route: ActivatedRoute,
    private uiConfigService: UiConfigService,
    private programsService: ProgramsService,
    public dialog: MatDialog,
    private location: Location,
    public utilService: UtilsService,
  ) {}

  async ngOnInit() {
    this.sub = this.route.paramMap.subscribe((params) => {
      this.partnerId = params.get("id");
    });
    await this.getCurrentPartner(this.partnerId);
    // this.data = history.state || new Partner();
    if (!this.data.isHostingPartner) {
      this.data.isHostingPartner = false;
    }
    if (!this.data.timezone) {
      this.data.timezone = 'UTC'
    }
    this.config =
      (await this.uiConfigService.getFormViewConfig('partners')) || {};
    this.data.program = this.data.program?._id || this.data.program;
    this.routeSub = this.route.url.subscribe((url) => {
      this.isEdit = url[0]?.path === 'edit';
      this.partnerAction = url[0]?.path;
    });
    this.config.commonProperties =
      await this.uiConfigService.importCommonProperties();

    await this.getData();
    this.timeZoneOptions = this.enumData.timeZone
    this.partnerTypeOptions = this.enumData.PartnerType
    this.deletePermission = await this.utilService.checkPerms({FX_Partner: ['delete']})
  }

  ngOnDestroy() {
    this.routeSub.unsubscribe();
    this.sub.unsubscribe();
  }
  
  async getCurrentPartner(id) {
    if (!id) {
      this.data = {};
      return;
    }
    let data = [];
    try {
      let query = JSON.stringify({ _id: id })
      data = await firstValueFrom(this.partnersService.getPartners({ query }));
    } catch (err) {
      this.alertService.errorAlert(
        (err && err.errorMessage) || sharedConstants.defaultErrorMessage,
      );
    }
    this.data = data[0] || {};
  }
  handleIsModifiedChange(isModified: boolean) {
    this.isModified = isModified;
  }

  canDeactivate(): boolean | Observable<boolean> {
    if (!this.isModified) {
      return true;
    }

    const dialogRef = this.dialog.open(ConfirmationDialog, {
      data: {
        schema: 'Unsaved Changes',
        content: `There are unsaved changes. Exit without saving?`,
        confirmButton: 'Proceed',
        cancelButton: 'Cancel',
      },
    });

    return dialogRef.afterClosed();
  }

  edit(row: any): void {
    this.router.navigate([`partners/edit/${row._id}`]);
  }

  delete(row: any): void {
    if (!this.deletePermission) {
      return;
    }
    this.dialog.open(ConfirmationDialog, {
      data: {
        data: row,
        schema: 'Delete Partner',
        content: `Are you sure that you want to delete <strong>${row.name}</strong>?`,
        confirmButton: 'Yes, Delete',
        cancelButton: 'No',
        confirmation: this.confirmationDialog.bind(this),
      },
    });
  }

  navigate() {
    if (history.state?.source !== 'partners') {
      this.location.back();
    } else {
      this.router.navigate(['partner/list']);
    }
  }

  async confirmationDialog(row) {
    try {
      await firstValueFrom(this.partnersService.deletePartner(row));
      this.alertService.successAlert('Partner deleted successfully');
      this.isModified = false;
      this.navigate();
    } catch (err) {
      this.alertService.errorAlert(err.errorMessage || 'Cannot delete partner');
    }
  }

  async getData() {
    const query = {
      query: JSON.stringify({
        type: { $in: ['PartnerType', 'timeZone', 'PartnerStat'] },
        lang: 'en',
      }),
      select: 'label,type,value',
    };

    try {
      this.program = await firstValueFrom(
        this.programsService.getProgramDetails(),
      );
    } catch (err) {
      this.alertService.errorAlert(err.errorMessage);
    }
    const enums = await firstValueFrom(this.programsService.getEnums(query));

    for (const x of enums) {
      if (!this.enumData[x.type]) {
        this.enumData[x.type] = [];
      }
      this.enumData[x.type].push(x);
    }
    this.enumData.program = this.program;
  }

  updateFormGroup(formGroup: FormGroup) {
    this.formGroup = formGroup;
    this.formGroup.controls['partnerFormControl']?.valueChanges.subscribe(
      (searchTerm) => {
        this.enumData.PartnerType = this.filterOptions(searchTerm, this.partnerTypeOptions);
      },
    );
    this.formGroup.controls['timeZoneFormControl']?.valueChanges.subscribe(
      (searchTerm) => {
        this.enumData.timeZone = this.filterOptions(searchTerm, this.timeZoneOptions);
      },
    );
  }
  ngOnChanges() {
    this.enumData.timeZone = this.timeZoneOptions || [];
    this.enumData.PartnerType = this.partnerTypeOptions || [];
  }

  filterOptions(searchTerm: string, options) {
    return options.filter((timezone) =>
        timezone.label.toLowerCase().includes(searchTerm.toLowerCase()),
      );
  }
  async savePartner() {
    this.isModified = false;
    try {
      await firstValueFrom(
        this.partnersService.updatePartner(this.data, this.isEdit),
      );
      this.alertService.successAlert('Partner saved successfully');
      this.router.navigate(['partners']);
    } catch (err) {
      this.alertService.errorAlert(
        err.errorMessage || sharedConstants.defaultErrorMessage,
      );
    }
  }
}

<div class="create-partner">
  <div class="headerContainer">
    <div class="left-elements">
      <div class="left-child">
        <div class="back-circle">
          <div
            class="circle"
            [routerLink]="['/partners']"
            routerLinkActive="router-link-active">
            <mat-icon class="back" svgIcon="back">arrow_back</mat-icon>
          </div>
        </div>
      </div>
      <div class="right-child">
        <div class="bread-crum">Partners</div>
        <div
          class="template-label"
          matTooltip
          matTooltipClass="custom-tooltip"
          IsEllipsisActive
          ellipsisData="{{formGroup.controls['name']?.value}}">
          {{formGroup.controls['name']?.value}}
        </div>
      </div>
    </div>

    <div class="right-elements">
      <button
        *ngIf="partnerAction === 'edit' || partnerAction === 'create'"
        class="theme-button active-btn"
        mat-flat-button
        aria-label="Edit Partner"
        [disabled]="!formGroup.valid"
        (click)="savePartner()">
        <mat-icon svgIcon="save"></mat-icon>Save
      </button>
      <button
        *ngIf="partnerAction === 'detail'"
        [disabled]="!utilService.checkPerms({FX_Partner: ['update']})"
        class="theme-button active-btn" 
        mat-flat-button
        aria-label="Edit Partner"
        (click)="edit(data)">
        <mat-icon svgIcon="edit-white"></mat-icon>Edit
      </button>
    </div>
  </div>

  <div class="childContainer">
    <div class="inner-headerContainer">
      <div class="left-elements">
        <div class="right-child">
          <div class="temp-properties-name">Partner Details</div>
        </div>
      </div>
    </div>
    <div class="main-container">
      <div class="full-width">
        <app-dynamic-form
          *ngIf="config"
          [config]="config"
          [data]="data"
          [title]="'Partnerdata'"
          [requiredData]="enumData"
          (formStatus)="updateFormGroup($event)"
          (isModifiedChanged)="handleIsModifiedChange($event)">
        </app-dynamic-form>
      </div>
    </div>
    <div class="delete-container">
      <app-delete-button
        [disableButton]="!deletePermission"
        (click)="delete(data)"
        *ngIf="partnerAction ==='detail' || partnerAction === 'edit'"
        >Delete Partner</app-delete-button
      >
    </div>
  </div>
</div>

// app/src/pages/Partner/CreatePartner.tsx
import React, { useState, useEffect, useRef } from 'react';
import { useNavigate, useParams, useLocation } from 'react-router-dom';

import { 
  Typography, 
  Button, 
  IconButton, 
  Card, 
  CardContent 
} from '@mui/material';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import SaveIcon from '@mui/icons-material/Save';
import { DynamicForm, DeleteButton } from '../../components/common';
import { useUtils } from '../../services/utils/useUtils';
import { useAlert } from '../../services/alert/useAlert';
import { useDialog } from '../../services/dialog/useDialog';
import { Partner } from '../../models/partner';

const CreatePartner: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const location = useLocation();
  
  const [formGroup, setFormGroup] = useState<any>(null);
  const [data, setData] = useState<Partner>(new Partner());
  const [isEdit, setIsEdit] = useState(false);
  const [partnerAction, setPartnerAction] = useState('create');
  const [enumData, setEnumData] = useState<{PartnerType?: any}>({});
  const [isModified, setIsModified] = useState(false);
  const [timeZoneOptions, setTimeZoneOptions] = useState<any[]>([]);
  const [partnerTypeOptions, setPartnerTypeOptions] = useState<any[]>([]);
  const [deletePermission, setDeletePermission] = useState(false);
  
  const { checkPerms } = useUtils();
  const { successAlert, errorAlert } = useAlert();
  const { openDialog } = useDialog();
  
  useEffect(() => {
    // Determine if we're in edit or view mode based on the URL
    const path = window.location.pathname.split('/')[2];
    setIsEdit(path === 'edit');
    setPartnerAction(path);
    
    // Check delete permission
    const checkDeletePermission = async () => {
      const hasPermission = await checkPerms({ FX_Partner: ['delete'] });
      setDeletePermission(hasPermission);
    };
    
    checkDeletePermission();
    
    // Get current partner if editing or viewing
    if (id) {
      getCurrentPartner(id);
    }
    
    // Initialize data
    if (!data.isHostingPartner) {
      setData(prev => ({ ...prev, isHostingPartner: false }));
    }
    if (!data.timezone) {
      setData(prev => ({ ...prev, timezone: 'UTC' }));
    }
    
    // Get required data
    getData();
  }, [id]);

  const getCurrentPartner = async (partnerId: string) => {
    if (!partnerId) return;
    
    try {
      // This would fetch the partner from an API
      // For now, we'll just set some dummy data
      const partnerData = {
        _id: partnerId,
        name: 'Partner ' + partnerId,
        code: 'P' + partnerId,
        partnerType: 'Supplier',
        email: `partner${partnerId}@example.com`,
        phone: '+1234567890',
        timezone: 'UTC',
        isHostingPartner: false
      };
      
      setData(partnerData as Partner);
    } catch (err: any) {
      errorAlert(err.errorMessage || 'Something went wrong. Please try again later.');
    }
  };

  const handleIsModifiedChange = (modified: boolean) => {
    setIsModified(modified);
  };

  const canDeactivate = () => {
    if (!isModified) {
      return true;
    }

    return new Promise<boolean>((resolve) => {
      openDialog({
        schema: 'Unsaved Changes',
        content: 'There are unsaved changes. Exit without saving?',
        confirmButton: 'Proceed',
        cancelButton: 'Cancel',
        onConfirm: () => resolve(true),
        onClose: () => resolve(false)
      });
    });
  };

  const edit = (row: any) => {
    navigate(`/partners/edit/${row._id}`);
  };

  const deletePartner = () => {
    if (!deletePermission) return;
    
    openDialog({
      schema: 'Delete Partner',
      content: `Are you sure that you want to delete <strong>${data.name}</strong>?`,
      confirmButton: 'Yes, Delete',
      cancelButton: 'No',
      onConfirm: confirmation
    });
  };

  const navigateTo = () => {
    if (location.state?.source !== 'partners') {
      window.history.back();
    } else {
      navigate('/partner/list');
    }
  };

  const confirmation = async () => {
    try {
      // This would delete the partner via API
      // await deletePartner(data);
      successAlert('Partner deleted successfully');
      setIsModified(false);
      navigateTo();
    } catch (err: any) {
      errorAlert(err.errorMessage || 'Cannot delete partner');
    }
  };

  const getData = async () => {
    try {
      // This would fetch enums and programs from APIs
      // For now, we'll just set some dummy data
      const enums = [
        { type: 'PartnerType', label: 'Supplier', value: 'Supplier' },
        { type: 'PartnerType', label: 'Customer', value: 'Customer' },
        { type: 'PartnerType', label: 'Distributor', value: 'Distributor' },
        { type: 'timeZone', label: 'UTC', value: 'UTC' },
        { type: 'timeZone', label: 'EST', value: 'EST' },
        { type: 'timeZone', label: 'PST', value: 'PST' }
      ];
      
      const programs = [
        { _id: '1', name: 'Program 1' },
        { _id: '2', name: 'Program 2' }
      ];
      
      // Process enums
      const enumDataObj: any = {};
      for (const x of enums) {
        if (!enumDataObj[x.type]) {
          enumDataObj[x.type] = [];
        }
        enumDataObj[x.type].push(x);
      }
      
      enumDataObj.program = programs;
      setEnumData(enumDataObj);
      
      // Set timezone and partner type options
      setTimeZoneOptions(enumDataObj.timeZone || []);
      setPartnerTypeOptions(enumDataObj.PartnerType || []);
    } catch (err: any) {
      errorAlert(err.errorMessage || 'Error fetching data');
    }
  };

  const updateFormGroup = (formGroupData: any) => {
    setFormGroup(formGroupData);
    
    // Add search filtering for partner type and timezone
    if (formGroupData.controls?.partnerFormControl?.valueChanges) {
      formGroupData.controls.partnerFormControl.valueChanges.subscribe((searchTerm: string) => {
        setEnumData(prev => ({
          ...prev,
          PartnerType: filterOptions(searchTerm, partnerTypeOptions)
        }));
      });
    }
    
    if (formGroupData.controls?.timeZoneFormControl?.valueChanges) {
      formGroupData.controls.timeZoneFormControl.valueChanges.subscribe((searchTerm: string) => {
        setEnumData(prev => ({
          ...prev,
          timeZone: filterOptions(searchTerm, timeZoneOptions)
        }));
      });
    }
  };

  const filterOptions = (searchTerm: string, options: any[]) => {
    return options.filter((option) =>
      option.label.toLowerCase().includes(searchTerm.toLowerCase())
    );
  };

  const savePartner = async () => {
    setIsModified(false);
    try {
      // This would save the partner via API
      // await updatePartner(data, isEdit);
      successAlert('Partner saved successfully');
      navigate('/partners');
    } catch (err: any) {
      errorAlert(err.errorMessage || 'Something went wrong. Please try again later.');
    }
  };

  const getClassName = () => {
    return `status status-${data.status?.toLowerCase().split(' ').join('') || 'revision'}`;
  };

  return (
    <div className="bg-white">
      {/* Header */}
      <div className="flex justify-between items-center px-7 py-4 border-b border-gray-200">
        <div className="flex items-center">
          <div className="mr-4">
            <IconButton 
              className="border border-gray-200 rounded-full"
              onClick={navigateTo}
            >
              <ArrowBackIcon />
            </IconButton>
          </div>
          <div>
            <Typography variant="body2" className="text-gray-700">Partners</Typography>
            <Typography variant="h6" className="font-semibold">
              {formGroup?.controls?.['name']?.value || data.name || ''}
            </Typography>
          </div>
        </div>
        
        <div className="flex gap-2">
          {partnerAction === 'edit' || partnerAction === 'create' ? (
            <Button
              variant="contained"
              startIcon={<SaveIcon />}
              onClick={savePartner}
              disabled={!formGroup?.valid}
              className="bg-blue-800 hover:bg-blue-900"
            >
              Save
            </Button>
          ) : (
            <Button
              variant="contained"
              startIcon={<span className="material-icons">edit</span>}
              onClick={() => edit(data)}
              disabled={!checkPerms({ FX_Partner: ['update'] })}
              className="bg-blue-800 hover:bg-blue-900"
            >
              Edit
            </Button>
          )}
        </div>
      </div>
      
      {/* Main Content */}
      <div className="p-6">
        <Card className="border border-gray-200 rounded-t-lg">
          <div className="flex items-center px-5 py-6 border-b border-gray-200">
            <Typography variant="h6" className="font-semibold">
              Partner Details
            </Typography>
            
            {partnerAction !== 'create' && (
              <div className="ml-4 px-3 py-1 text-xs font-medium rounded border border-amber-500 text-amber-800">
                {data.status || 'Revision'}
              </div>
            )}
            
            {partnerAction !== 'view' && (
              <div className="ml-4 px-3 py-1 text-xs font-medium rounded border border-blue-500 text-blue-800">
                Edit Mode
              </div>
            )}
            
            {partnerAction === 'view' && (
              <div className="ml-4 px-3 py-1 text-xs font-medium rounded border border-gray-500 text-gray-800">
                View Mode
              </div>
            )}
          </div>
          
          <CardContent>
            {/* Dynamic Form */}
            {Object.keys(enumData).length > 0 && (
              <DynamicForm
                config={{
                  data: {
                    Partnerdata: {
                      dataFields: [
                        {
                          fields: [
                            {
                              field: 'name',
                              label: 'Partner Name',
                              type: 'text',
                              required: true
                            },
                            {
                              field: 'partnerType',
                              label: 'Partner Type',
                              type: 'select-search',
                              selectData: 'PartnerType',
                              selectLabel: 'label',
                              selectValue: 'value',
                              required: true,
                              formControl: 'partnerFormControl'
                            },
                            {
                              field: 'code',
                              label: 'Code',
                              type: 'text',
                              required: true
                            },
                            {
                              field: 'email',
                              label: 'Support Email',
                              type: 'text',
                              required: true,
                              regExp: '^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,4}$'
                            },
                            {
                              field: 'phone',
                              label: 'Support Number',
                              type: 'text'
                            },
                            {
                              field: 'timezone',
                              label: 'Timezone',
                              type: 'select-search',
                              selectData: 'timeZone',
                              selectLabel: 'label',
                              selectValue: 'value',
                              required: true,
                              formControl: 'timeZoneFormControl'
                            },
                            {
                              field: 'isHostingPartner',
                              label: 'Hosting Partner',
                              type: 'switch'
                            }
                          ]
                        }
                      ]
                    }
                  }
                }}
                data={data}
                title="Partnerdata"
                requiredData={enumData}
                formStatus={updateFormGroup}
                isModifiedChanged={handleIsModifiedChange}
              />
            )}
          </CardContent>
        </Card>
        
        {/* Delete Button */}
        <div className="mt-4">
          {(partnerAction === 'detail' || partnerAction === 'edit') && (
            <DeleteButton 
              onClick={deletePartner} 
              disableButton={!deletePermission}
            >
              Delete Partner
            </DeleteButton>
          )}
        </div>
      </div>
    </div>
  );
};

export default CreatePartner;
