// app/common-components/drop-down-with-search/drop-down-with-search.component.ts
import {
  AfterViewInit,
  Component,
  EventEmitter,
  Input,
  OnDestroy,
  OnInit,
  Output,
  ViewChild,
} from '@angular/core';
import { FormControl } from '@angular/forms';
import { MatSelect } from '@angular/material/select';
import { ReplaySubject, Subject, take, takeUntil } from 'rxjs';
import { UiConfigService } from 'src/app/shared/services/ui-config.service';

export interface Options {
  id: string;
  name: string;
}

@Component({
  selector: 'app-drop-down-with-search',
  templateUrl: './drop-down-with-search.component.html',
  styleUrls: ['./drop-down-with-search.component.scss'],
})
export class DropDownWithSearchComponent
  implements OnInit, AfterViewInit, OnDestroy {
  @Input() placeHolder = 'Select Value';
  @Input() label = '';
  @Input() placeHolderSearchBox = 'Select Value';
  @Input() selectedValue: any[] = [];
  @Input() selectBoxOptions: Options[];
  @Input() callBack: Function;
  @Input() multiple = false;
  @Output() valueChange = new EventEmitter();
  @Input() fieldName: string;
  // inputValue: any[] = this.selectedValue;
  dropDownEllipsis: any = {};
  ellipsisData = '';

  /** control for the selected bank for multi-selection */
  public selectCtrl: FormControl<any> = new FormControl<any>(null);
  @ViewChild('multiSelect', { static: true }) multiSelect: MatSelect;

  /** control for the MatSelect filter keyword */
  public selectFilterCtrl: FormControl<string | null> = new FormControl<string>(
    '',
  );

  /** list of Options filtered by search keyword */
  public filteredOptions: ReplaySubject<Options[]> = new ReplaySubject<
    Options[]
  >(1);

  /** local copy of filtered banks to help set the toggle all checkbox state */
  protected filteredOptionsCache: Options[] = [];

  /** flags to set the toggle all checkbox state */
  isIndeterminate = false;
  isChecked = false;

  /** Subject that emits when the component has been destroyed. */
  protected _onDestroy = new Subject<void>();

  constructor(private uiConfigService: UiConfigService) {}

  async ngOnInit() {
    // set initial selection
    this.selectCtrl.setValue([]);
    const ellipsisProperty =
      await this.uiConfigService.importCommonProperties('dropDownEllipsis');

    if (ellipsisProperty) {
      this.dropDownEllipsis = ellipsisProperty;
    }
    // this.filteredOptions.next(this.selectBoxOptions.slice());

    // listen for search field value changes
    this.selectFilterCtrl.valueChanges
      .pipe(takeUntil(this._onDestroy))
      .subscribe(() => {
        this.filterOptionsMulti();
        this.setToggleAllCheckboxState();
      });

    // listen for multi select field value changes
    this.selectCtrl.valueChanges
      .pipe(takeUntil(this._onDestroy))
      .subscribe(() => {
        this.setToggleAllCheckboxState();
      });
  }

  ngAfterViewInit() {
    this.setInitialValue();
  }

  ngOnChanges() {
    this.selectBoxOptions =
      this.selectBoxOptions?.filter((obj) => {
        return obj && obj.name;
      }) || [];
    this.filteredOptions.next(
      this.selectBoxOptions
        .sort((a, b) => a?.name?.localeCompare(b?.name))
        .slice(),
    );
    this.selectCtrl.setValue(this.selectedValue || []);
    this.filterOptionsMulti();
  }

  protected setInitialValue() {
    this.filteredOptions
      .pipe(take(1), takeUntil(this._onDestroy))
      .subscribe(() => {
        if (this.multiSelect)
          this.multiSelect.compareWith = (a: Options, b: Options) =>
            a && b && a.id === b.id;
      });
  }

  ngOnDestroy() {
    this._onDestroy.next();
    this._onDestroy.complete();
  }

  protected filterOptionsMulti() {
    if (!this.selectBoxOptions) {
      return;
    }
    // get the search keyword
    let search = this.selectFilterCtrl.value;

    if (!search) {
      this.filteredOptionsCache = this.selectBoxOptions.slice();
      this.filteredOptions.next(this.filteredOptionsCache);

      // this.selectCtrl.setValue([]);
      // this.onInputValueChange();
      return;
    } else {
      search = search.toLowerCase();
    }
    // filter the banks
    this.filteredOptionsCache = this.selectBoxOptions.filter(
      (option) => option.name.toLowerCase().indexOf(search) > -1,
    );
    this.filteredOptions.next(this.filteredOptionsCache);
  }

  toggleSelectAll(selectAllValue: boolean) {
    this.filteredOptions
      .pipe(take(1), takeUntil(this._onDestroy))
      .subscribe((val) => {
        if (selectAllValue) {
          this.selectCtrl.patchValue(val);
        } else {
          this.selectCtrl.patchValue([]);
        }
      });
    this.onInputValueChange();
  }

  protected setToggleAllCheckboxState() {
    let filteredLength = 0;

    this.ellipsisData = this.selectCtrl?.value
      ?.map((item) => item.name)
      .join(', ');
    if (this.selectCtrl && this.selectCtrl.value) {
      const optionsSelected = this.filteredOptionsCache?.length
        ? this.filteredOptionsCache
        : this.selectBoxOptions;

      optionsSelected &&
        optionsSelected.forEach((el) => {
          this.selectCtrl.value.forEach((element) => {
            if (el.name === element.name) {
              filteredLength++;
            }
          });
        });
      this.isChecked =
        filteredLength > 0 && filteredLength === optionsSelected.length;
    }
  }

  calculateEllipsisMaxLength(): number | null {
    if (
      this.selectCtrl?.value?.length > 1 &&
      this.selectCtrl?.value?.length != this.selectBoxOptions?.length
    ) {
      return this.dropDownEllipsis?.multiSelectedMaxLength;
    }
    if (this.selectCtrl?.value?.length === 1) {
      return this.dropDownEllipsis?.singleSelectedMaxLength;
    }

    return null;
  }

  getEllipsisData(): string {
    if (this.selectCtrl?.value?.length === this.selectBoxOptions?.length) {
      return 'All Selected';
    } else {
      return this.ellipsisData;
    }
  }

  onInputValueChange() {
    const options = {
      input: this.selectCtrl.value || '',
      fieldName: this.fieldName,
    };
    this.valueChange.emit(options)
  }
}

// app/src/components/common/DropDownWithSearch/DropDownWithSearch.tsx
import React, { useState, useEffect, useRef } from 'react';
import { 
  FormControl, 
  InputLabel, 
  Select, 
  MenuItem, 
  Checkbox, 
  ListItemText, 
  TextField,
  Tooltip
} from '@mui/material';

interface Option {
  id: string;
  name: string;
}

interface DropDownWithSearchProps {
  placeHolder?: string;
  label?: string;
  placeHolderSearchBox?: string;
  selectedValue?: Option[];
  selectBoxOptions?: Option[];
  callBack?: Function;
  multiple?: boolean;
  fieldName?: string;
  valueChange?: (options: { input: Option[]; fieldName?: string }) => void;
}

const DropDownWithSearch: React.FC<DropDownWithSearchProps> = ({
  placeHolder = 'Select Value',
  label = '',
  placeHolderSearchBox = 'Select Value',
  selectedValue = [],
  selectBoxOptions = [],
  callBack,
  multiple = false,
  fieldName,
  valueChange
}) => {
  const [selectCtrl, setSelectCtrl] = useState<Option[]>(selectedValue || []);
  const [selectFilterCtrl, setSelectFilterCtrl] = useState<string>('');
  const [filteredOptions, setFilteredOptions] = useState<Option[]>([]);
  const [isOpen, setIsOpen] = useState(false);
  const [isIndeterminate, setIsIndeterminate] = useState(false);
  const [isChecked, setIsChecked] = useState(false);
  const selectRef = useRef<HTMLDivElement>(null);
  const [ellipsisData, setEllipsisData] = useState('');

  // Initialize filtered options
  useEffect(() => {
    setFilteredOptions(selectBoxOptions?.sort((a, b) => a.name.localeCompare(b.name)) || []);
  }, [selectBoxOptions]);

  // Update selected values when prop changes
  useEffect(() => {
    setSelectCtrl(selectedValue || []);
  }, [selectedValue]);

  // Filter options based on search term
  useEffect(() => {
    if (!selectBoxOptions) return;
    
    const filtered = selectFilterCtrl
      ? selectBoxOptions.filter(option => 
          option.name.toLowerCase().includes(selectFilterCtrl.toLowerCase())
        )
      : selectBoxOptions;
    
    setFilteredOptions(filtered.sort((a, b) => a.name.localeCompare(b.name)));
    setToggleAllCheckboxState();
  }, [selectFilterCtrl, selectBoxOptions]);

  // Update toggle all checkbox state
  useEffect(() => {
    setToggleAllCheckboxState();
  }, [selectCtrl]);

  const setToggleAllCheckboxState = () => {
    if (!selectCtrl || !filteredOptions.length) {
      setIsChecked(false);
      setIsIndeterminate(false);
      return;
    }

    const ellipsisText = selectCtrl.map(item => item.name).join(', ');
    setEllipsisData(ellipsisText);

    let filteredLength = 0;
    const optionsSelected = filteredOptions.length ? filteredOptions : selectBoxOptions;

    optionsSelected?.forEach(el => {
      selectCtrl.forEach(element => {
        if (el.name === element.name) {
          filteredLength++;
        }
      });
    });

    setIsChecked(filteredLength > 0 && filteredLength === optionsSelected.length);
    setIsIndeterminate(filteredLength > 0 && filteredLength < optionsSelected.length);
  };

  const handleChange = (event: React.ChangeEvent<{ value: unknown }>) => {
    const value = event.target.value as Option[];
    setSelectCtrl(value);
    onInputValueChange();
  };

  const toggleSelectAll = (selectAllValue: boolean) => {
    if (selectAllValue) {
      setSelectCtrl([...filteredOptions]);
    } else {
      setSelectCtrl([]);
    }
    onInputValueChange();
  };

  const onInputValueChange = () => {
    const options = {
      input: selectCtrl || '',
      fieldName
    };
    
    if (valueChange) {
      valueChange(options);
    }
  };

  const calculateEllipsisMaxLength = (): number | null => {
    if (selectCtrl.length > 1 && selectCtrl.length !== selectBoxOptions.length) {
      return 20; // multiSelectedMaxLength
    }
    if (selectCtrl.length === 1) {
      return 30; // singleSelectedMaxLength
    }
    return null;
  };

  const getEllipsisData = (): string => {
    if (selectCtrl.length === selectBoxOptions.length) {
      return 'All Selected';
    } else {
      return ellipsisData;
    }
  };

  const renderValue = (selected: Option[]) => {
    if (selected.length === 0) {
      return <span>{placeHolder}</span>;
    }

    const maxLength = calculateEllipsisMaxLength();
    let displayText = selected[0].name;
    
    if (selected.length > 1) {
      if (selected.length === selectBoxOptions.length) {
        displayText = 'All Selected';
      } else if (maxLength && ellipsisData.length > maxLength) {
        displayText = `${selected[0].name} (+${selected.length - 1} ${selected.length === 2 ? 'other' : 'others'})`;
      } else {
        displayText = `${selected[0].name} (+${selected.length - 1} ${selected.length === 2 ? 'other' : 'others'})`;
      }
    }

    return (
      <Tooltip title={getEllipsisData()} placement="top" arrow>
        <span className="truncate">{displayText}</span>
      </Tooltip>
    );
  };

  return (
    <FormControl variant="outlined" fullWidth className="mb-4">
      {label && <InputLabel>{label}</InputLabel>}
      
      <Select
        multiple={multiple}
        value={selectCtrl}
        onChange={handleChange}
        renderValue={multiple ? (selected) => renderValue(selected as Option[]) : undefined}
        placeholder={placeHolder}
        onOpen={() => setIsOpen(true)}
        onClose={() => setIsOpen(false)}
        ref={selectRef}
        label={label}
      >
        {isOpen && (
          <MenuItem disabled>
            <div className="p-2 w-full">
              <TextField
                fullWidth
                variant="outlined"
                placeholder={placeHolderSearchBox}
                value={selectFilterCtrl}
                onChange={(e) => setSelectFilterCtrl(e.target.value)}
                onClick={(e) => e.stopPropagation()}
                size="small"
              />
              {multiple && (
                <div className="flex items-center mt-2">
                  <Checkbox
                    indeterminate={isIndeterminate}
                    checked={isChecked}
                    onChange={(e) => toggleSelectAll(e.target.checked)}
                  />
                  <span>Select All</span>
                </div>
              )}
            </div>
          </MenuItem>
        )}
        
        {filteredOptions.map((option) => (
          <MenuItem key={option.id} value={option}>
            {multiple && (
              <Checkbox checked={selectCtrl.some(item => item.id === option.id)} />
            )}
            <Tooltip title={option.name} placement="top" arrow>
              <ListItemText 
                primary={option.name} 
                className="truncate max-w-xs"
              />
            </Tooltip>
          </MenuItem>
        ))}
      </Select>
    </FormControl>
  );
};

export default DropDownWithSearch;
