// app/src/components/common/TableFilter/TableFilter.tsx
import React, { useState, useEffect } from 'react';
import { 
  Button,
  TextField,
  InputAdornment,
  FormControl
} from '@mui/material';
import { DateRangePicker } from '@mui/x-date-pickers-pro/DateRangePicker';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFns';
import SearchIcon from '@mui/icons-material/Search';
import RefreshIcon from '@mui/icons-material/Refresh';
import StatusFilter from '../StatusFilter/StatusFilter';
import DropDownWithSearch from '../DropDownWithSearch/DropDownWithSearch';

interface TableFilterProps {
  config: any;
  handlers?: any;
  tableData?: any[];
  searchValue?: string;
  startDate?: string | null;
  endDate?: string | null;
  statusFilter?: string;
  pageName?: string;
  filterChange?: (options: any) => void;
  startTimeChange?: (date: string | null) => void;
  endTimeChange?: (date: string | null) => void;
  statusChange?: (status: string) => void;
  inputChange?: (value: string) => void;
  searchValueChange?: (options: { input: string }) => void;
}

const TableFilter: React.FC<TableFilterProps> = ({
  config,
  handlers = {},
  tableData = [],
  searchValue = '',
  startDate = null,
  endDate = null,
  statusFilter = 'all',
  pageName = '',
  filterChange,
  startTimeChange,
  endTimeChange,
  statusChange,
  inputChange,
  searchValueChange
}) => {
  const [cfgOpt, setCfgOpt] = useState<any>({});
  const [range, setRange] = useState<[Date | null, Date | null]>([null, null]);
  const [refresh, setRefresh] = useState(false);
  const [inputFieldValue, setInputFieldValue] = useState<any[]>([]);

  useEffect(() => {
    if (config?.filterOptions) {
      setCfgOpt(config.filterOptions);
    }
    
    setRefresh(config?.refresh ?? false);
    
    // Initialize date range if provided
    if (startDate) {
      const start = new Date(startDate);
      const end = endDate ? new Date(endDate) : null;
      setRange([start, end]);
    }
  }, [config, startDate, endDate]);

  const getRefreshData = () => {
    if (handlers && typeof handlers.getRefresh === 'function') {
      handlers.getRefresh();
    }
  };

  const onStartDateChange = (date: Date | null) => {
    if (startTimeChange) {
      const formattedDate = date ? formatDate(date, 'start') : null;
      startTimeChange(formattedDate);
    }
  };

  const onEndDateChange = (date: Date | null) => {
    if (endTimeChange) {
      const formattedDate = date ? formatDate(date, 'end') : null;
      endTimeChange(formattedDate);
    }
  };

  const formatDate = (date: Date, type: 'start' | 'end'): string => {
    if (!date) return '';
    
    // Clone the date to avoid modifying the original
    const newDate = new Date(date);
    
    // Set to start or end of day
    if (type === 'start') {
      newDate.setHours(0, 0, 0, 0);
    } else {
      newDate.setHours(23, 59, 59, 999);
    }
    
    return newDate.toISOString();
  };

  const onStatusChange = (status: string) => {
    if (statusChange) {
      statusChange(status);
    }
  };

  const onChange = (options: any, field?: string) => {
    if (filterChange) {
      filterChange(options);
    }
  };

  const onInputValueChange = (value: string) => {
    if (inputChange) {
      inputChange(value);
    }
  };

  const onSearchValueChange = (options: { input: string }) => {
    if (searchValueChange) {
      searchValueChange(options);
    }
  };

  const resetFilters = () => {
    setRange([null, null]);
    
    if (statusChange) statusChange('all');
    if (startTimeChange) startTimeChange(null);
    if (endTimeChange) endTimeChange(null);
    if (searchValueChange) searchValueChange({ input: '' });
    if (filterChange) filterChange({ input: [], fieldName: '' });
    
    setInputFieldValue([]);
  };

  const getSelectedValue = (list: any[] = [], fieldName: string) => {
    const filters = config.filters?.[fieldName] || [];
    return list.filter(l => filters.includes(l.name));
  };

  // Helper function to maintain original order
  const originalOrder = () => 0;

  return (
    <div className="table-filter-section">
      <div className="flex justify-between items-center p-4 border-b border-gray-200">
        <StatusFilter 
          statusFilter={statusFilter} 
          onFilterChange={onStatusChange} 
        />
        
        <div className="flex items-center">
          <TextField
            placeholder="Search by Integration Name or Run Id"
            variant="outlined"
            size="small"
            value={searchValue}
            onChange={(e) => onSearchValueChange({ input: e.target.value })}
            InputProps={{
              startAdornment: (
                <InputAdornment position="start">
                  <SearchIcon className="text-gray-400" />
                </InputAdornment>
              ),
            }}
            className="w-80"
          />
        </div>
      </div>
      
      <div className="flex justify-between items-center p-4 border-b border-gray-200">
        <div className="flex flex-wrap gap-4 flex-grow">
          {Object.entries(cfgOpt).map(([key, value]: [string, any]) => (
            <DropDownWithSearch
              key={key}
              placeHolder={value.placeholder}
              placeHolderSearchBox={value.searchplaceholder}
              label={value.label}
              multiple={true}
              selectBoxOptions={config[value.label] || []}
              selectedValue={getSelectedValue(config[value.label], value.field)}
              fieldName={value.field}
              valueChange={(options) => onChange(options, value.field)}
            />
          ))}
          
          <LocalizationProvider dateAdapter={AdapterDateFns}>
            <DateRangePicker
              localeText={{ start: 'Start date', end: 'End date' }}
              value={range}
              onChange={(newValue) => {
                setRange(newValue);
                onStartDateChange(newValue[0]);
                onEndDateChange(newValue[1]);
              }}
              slotProps={{
                textField: { size: 'small', fullWidth: true },
                fieldSeparator: { children: 'to' },
              }}
            />
          </LocalizationProvider>
        </div>
        
        <div className="flex gap-2">
          {refresh && (
            <Button
              variant="outlined"
              onClick={getRefreshData}
              startIcon={<RefreshIcon />}
            >
              Refresh
            </Button>
          )}
          
          <Button
            variant="outlined"
            onClick={resetFilters}
          >
            Reset Filters
          </Button>
        </div>
      </div>
    </div>
  );
};

export default TableFilter;

// app/common-components/table-filter/table-filter.component.ts
import {
  Component,
  EventEmitter,
  Input,
  OnInit,
  Output,
  SimpleChanges,
  ViewEncapsulation,
} from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';
import * as moment from 'moment';
import { UiConfigService } from 'src/app/shared/services/ui-config.service';
import { UtilsService } from 'src/app/shared/services/utils.service';

export interface Options {
  id: string;
  name: string;
}

@Component({
  selector: 'app-table-filter',
  templateUrl: './table-filter.component.html',
  styleUrls: ['./table-filter.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class TableFilterComponent implements OnInit {
  showSliderBar = false;
  runHistoryData: any;
  cfgOpt: any;
  inputValue = '';
  inputFieldValue: any[] = [];
  dataFromChild: any = [];
  refresh = false;
  @Input() searchValue;
  @Input() startDate: any = null;
  @Input() endDate: any = null;
  @Input() statusFilter;
  @Input() tableData;
  @Input() config;
  @Input() handlers;
  @Input() pageName;
  @Output() startTimeChange = new EventEmitter();
  @Output() endTimeChange = new EventEmitter();
  @Output() filterChange = new EventEmitter();
  @Output() inputChange = new EventEmitter();
  @Output() statusChange = new EventEmitter();
  @Output() searchValueChange = new EventEmitter();
  range = new FormGroup({
    start: new FormControl<Date | null>(null),
    end: new FormControl<Date | null>(null),
  });

  data: any;
  protected integrationNameOptions: Options[] = [];
  protected runIdOptions: Options[] = [];
  protected partnerNameOptions: Options[] = [];

  originalOrder = () => 0;

  constructor(
    private uiConfigService: UiConfigService,
    private utilsService: UtilsService
  ) {}

  async ngOnInit() {
    this.config =
      (await this.uiConfigService.getListViewConfig('run-history')) || {};
    this.cfgOpt = this.config?.filterOptions || {};
    this.refresh = this.config?.refresh ?? false;
    this.initializeDateRange();
  }

  initializeDateRange() {
    const searchHistory = this.utilsService.getPageFilters(this.pageName);
    if (searchHistory.startDate) {
      this.range.setValue({ start: searchHistory.startDate, end: searchHistory.endDate });
    }
  }

  getRefreshData() {
    if (this.handlers && typeof this.handlers.getRefresh === 'function') {
      this.handlers.getRefresh();
    }
  }

  async ngOnChanges(changes: SimpleChanges) {
    if (changes.startDate && changes.startDate.currentValue) {
      this.initializeDateRange();
    }
    this.getDropDownOptions(this.tableData);
    this.cfgOpt = this.config?.filterOptions;
    if (!this.data && this.tableData && this.tableData.length) {
      this.data = this.tableData;
      this.dataFromChild = [...this.data];
    }
    if (this.config && this.config.element && this.config.runId) {
      this.inputFieldValue = [this.config.element];
      this.config.element = '';
    }
  }

  getDropDownOptions(data) {
    if (!data) {
      return;
    }
    for (const i of data) {
      const runIdArray = this.runIdOptions.map((obj) => obj.name);
      const uniquerunIdSet = new Set(runIdArray);
      const uniquerunIdArray = Array.from(uniquerunIdSet);
      const intergrationNameArray = this.integrationNameOptions.map(
        (obj) => obj.name,
      );
      const uniqueIntegrationNameSet = new Set(intergrationNameArray);
      const uniqueIntegrationNameArray = Array.from(uniqueIntegrationNameSet);
      const partnerNameArray = this.partnerNameOptions.map((obj) => obj.name);
      const uniquePartnerNameSet = new Set(partnerNameArray);
      const uniquePartnerNameArray = Array.from(uniquePartnerNameSet);

      if (!uniquerunIdArray.includes(i.runId)) {
        const runIdObj = {
          name: i.runId,
          id: i._id,
        };

        this.runIdOptions.push(runIdObj);
      }
      if (i.integrationId) {
        if (!uniqueIntegrationNameArray.includes(i.integrationId.name)) {
          this.integrationNameOptions.push({
            name: i.integrationId.name,
            id: i.integrationId._id,
          });
        }
      }
      if (i.partner && !uniquePartnerNameArray.includes(i.partner.name)) {
        this.partnerNameOptions.push({
          name: i.partner.name,
          id: i.partner._id,
        });
      }
    }
    if (this.config) {
      this.config['Integration'] = this.integrationNameOptions;
      this.config['Run Id'] = this.runIdOptions;
      this.config['Partner'] = this.partnerNameOptions;
    }
  }

  showSlider() {
    this.showSliderBar = !this.showSliderBar;
  }

  formatLabel(totalMinutes: number): string {
    if (totalMinutes) {
      if (totalMinutes > 60) {
        const hours = Math.floor(totalMinutes / 60);
        const minutes = totalMinutes % 60;

        return `${hours} hr ${minutes} min`;
      } else {
        const fullDuration =
          totalMinutes === 60 ? `${totalMinutes} hr` : `${totalMinutes} min`;

        // this.duration = fullDuration;
        return fullDuration;
      }
    } else {
      return '';
    }
  }

  onChange(options) {
    this.filterChange.emit(options);
  }

  onStartDateChange() {
    this.startDate = this.getFormattedDate(
      moment(this.range.get('start').value).startOf('day'),
    );
    this.startTimeChange.emit(this.startDate);
  }

  onEndDateChange() {
    this.endDate = this.getFormattedDate(
      moment(this.range.get('end').value).endOf('day'),
    );
    this.endTimeChange.emit(this.endDate);
  }

  getFormattedDate(dateValue) {
    if (dateValue) {
      const formattedDate = dateValue.toISOString();

      return formattedDate;
    } else {
      return dateValue;
    }
  }

  onStatusChange(inputValue: string) {
    this.statusChange.emit(inputValue);
  }

  onInputValueChange(inputValue: string) {
    this.config.filters['searchValue'] = this.searchValue;
    this.inputValue = inputValue;
    this.inputChange.emit(this.inputValue);
  }

  resetFilters() {
    this.runIdOptions = [];
    this.integrationNameOptions = [];
    this.partnerNameOptions = [];
    this.statusFilter = 'all';
    this.inputFieldValue = [];
    this.config.filters = {};
    this.statusChange.emit('all');
    this.range.setValue({ start: null, end: null });
    this.filterChange.emit([[], '']);
    this.startTimeChange.emit(null);
    this.endTimeChange.emit(null);
    this.searchValueChange.emit({ input: '' });
    this.utilsService.resetPageFilters(this.pageName);
  }

  getSelectedValue(list = [], fieldName) {
    let filters = this.config.filters[fieldName] || [];
    if (!Array.isArray(filters)) {
      filters = [filters];
    }
    return list.filter(l => filters.includes(l.name));
  }

  onSearchValueChange(options) {
    this.searchValueChange.emit(options);
  }
}

<div class="table-filter-section">
  <div class="row search-section">
    <app-status-filter
      (filterChange)="onStatusChange($event)"
      [statusFilter]="statusFilter">
    </app-status-filter>
    <div class="right-elements">
      <mat-form-field appearance="outline">
        <mat-icon matPrefix svgIcon="magnifier" class="icon-small"></mat-icon>
        <input
          matInput
          type="search"
          placeholder="Search by Integration Name or Run Id"
          [(ngModel)]="searchValue"
          (input)="onSearchValueChange({ input: $event.target.value })" />
      </mat-form-field>
    </div>
  </div>
  <div class="row filter-section">
    <div class="filter-options">
      <app-drop-down-with-search
        *ngFor="let item of cfgOpt | keyvalue: originalOrder"
        [placeHolder]="item.value.placeholder"
        [placeHolderSearchBox]="item.value.searchplaceholder"
        [label]="item.value.label"
        [multiple]="true"
        [selectBoxOptions]="config[item.value.label]"
        [selectedValue]="getSelectedValue(config[item.value.label], item.value.field)"
        [fieldName]="item.value.field"
        (valueChange)="onChange($event)">
      </app-drop-down-with-search>
      <mat-form-field
        appearance="outline"
        floatLabel="always"
        class="date-range-picker"
        color="primary">
        <mat-label>Enter a date range</mat-label>
        <mat-date-range-input [formGroup]="range" [rangePicker]="picker">
          <input
            matStartDate
            formControlName="start"
            placeholder="Start date"
            (dateChange)="onStartDateChange()" />
          <input
            readonly
            matEndDate
            formControlName="end"
            placeholder="End date"
            (dateChange)="onEndDateChange()" />
        </mat-date-range-input>
        <mat-datepicker-toggle matIconSuffix [for]="picker">
          <mat-icon matDatepickerToggleIcon svgIcon="calendar"></mat-icon>
        </mat-datepicker-toggle>
        <mat-date-range-picker #picker></mat-date-range-picker>
        <mat-error *ngIf="range.controls.start.hasError('matStartDateInvalid')"
          >Invalid start date</mat-error
        >
        <mat-error *ngIf="range.controls.end.hasError('matEndDateInvalid')"
          >Invalid end date</mat-error
        >
      </mat-form-field>
    </div>
    <div class="filter-reset">
      <button
        mat-stroked-button
        *ngIf="refresh"
        class="refresh"
        (click)="getRefreshData()">
        <mat-icon svgIcon="refresh" class="refresh-icon"></mat-icon>
      </button>
      <button mat-stroked-button (click)="resetFilters()">Reset Filters</button>
    </div>
  </div>
</div>
