// app/src/pages/Templates/ResponseBodyPropertiesComponent.tsx
// ResponseBodyPropertiesComponent.tsx
import React, { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import DynamicForm from './DynamicForm';
import sharedConstants from 'src/shared';
import { useUiConfig } from '@/services/ui-config/useUiConfig';


interface RESPONSEBODYINTERFACE {
  rcxProcess?: string;
  inputFileLayout?: any;
}

interface Props {
  properties?: RESPONSEBODYINTERFACE;
  activeFieldDetails?: any;
  data?: any;
  enumData?: any;
  handlers?: any;
  valueFields?: any;
}

const ResponseBodyPropertiesComponent: React.FC<Props> = (props) => {
  const { properties, activeFieldDetails, data, enumData, handlers, valueFields } = props;
  const [config, setConfig] = useState<any>(null);
  const [valueOptions, setValueOptions] = useState<any>([]);
  const { register, handleSubmit, watch, formState } = useForm();

  const uiConfigService = useUiConfig();

  const options = ['String', 'Number'];

  const addHandler = () => {
    handlers.handleFieldNameUpdate = handleFieldNameUpdate;
  };

  const getValues = () => {
    const values = ['Error Code', 'Error Message', 'HTTP Status', 'Constant', 'Row Number'];
    if (properties?.rcxProcess === 'Activity') {
      values.push('ActivityId');
    }
    if (properties?.inputFileLayout?.bodyFieldDefs?.length) {
      for (const field of properties.inputFileLayout.bodyFieldDefs) {
        if (field.rcxField && !values.includes(field.rcxField)) {
          values.push(field.rcxField);
        }
      }
    }
    setValueOptions(values);
    enumData.valueOptions = values;
  };

  const handleFieldNameUpdate = (formData: any) => {
    if (
      (!formData.filedName ||
        formData.fieldName === sharedConstants.defaultFieldName ||
        valueOptions.includes(data.fieldName)) &&
      data.value
    ) {
      formData.fieldName = data.value;
    }
  };

  const updateFormGroup = (formData: any) => {
    // emit form data
    console.log(formData);
    // watch form changes
    watch((values) => {
      handlers.handleIsModifiedChange(true);
    });
  };

  const onSubmit = (formData: any) => {
    updateFormGroup(formData);
  };

  useEffect(() => {
    const fetchConfig = async () => {
      const configResponse = await uiConfigService.getFormViewConfig('templates');
      setConfig(configResponse || {});
    };
    fetchConfig();
    addHandler();
  }, []);

  useEffect(() => {
    if (properties && properties.inputFileLayout && properties.inputFileLayout.bodyFieldDefs) {
      getValues();
    }
  }, [properties, enumData]);

  return (
    <div className="form">
      {config && (
        <DynamicForm
          data={data}
          handlers={handlers}
          properties={properties}
          activeFieldDetails={activeFieldDetails}
          requiredData={enumData}
          config={config}
          title="responseBodyProperties"
          onSubmit={onSubmit}
        />
      )}
    </div>
  );
};

export default ResponseBodyPropertiesComponent;

// app/templates/common/response-body-properties/response-body-properties.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { sharedConstants } from 'src/app/shared';
import { UiConfigService } from 'src/app/shared/services/ui-config.service';

@Component({
  selector: 'app-response-body-properties',
  templateUrl: './response-body-properties.component.html',
  styleUrls: ['./response-body-properties.component.scss'],
})
export class ResponseBodyPropertiesComponent {
  options = ['String', 'Number'];

  @Input() properties;
  @Input() activeFieldDetails;
  @Input() data;
  @Input() enumData;
  @Input() handlers;
  @Input() valueFields;
  @Output() formStatus: EventEmitter<FormGroup> = new EventEmitter<FormGroup>();
  valueOptions;
  config: any;

  constructor(private uiConfigService: UiConfigService) {}

  async ngOnInit() {
    this.config =
      (await this.uiConfigService.getFormViewConfig('templates')) || {};
    this.addHandler();
  }

  ngOnChanges() {
    this.data = this.data || {};
    this.enumData = this.enumData || {};
    this.enumData.DataType = this.enumData.DataType || [];
    this.getValues();
  }

  getValues() {
    const values = ['Error Code', 'Error Message', 'HTTP Status', 'Constant', 'Row Number'];
    if (this.properties.rcxProcess === 'Activity') {
      values.push('ActivityId')
    }
    if (this?.properties?.inputFileLayout?.bodyFieldDefs?.length) {
      for (const field of this.properties.inputFileLayout.bodyFieldDefs) {
        if (field.rcxField && !values.includes(field.rcxField)) {
          values.push(field.rcxField);
        }
      }
    }
    this.valueOptions = values;
    this.enumData.valueOptions = this.valueOptions || [];
  }

  updateFormGroup(formGroup: FormGroup) {
    this.formStatus.emit(formGroup);
    formGroup.valueChanges.subscribe(() => {
      this.handlers.handleIsModifiedChange(true);
    });
  }

  addHandler() {
    this.handlers.handleFieldNameUpdate = this.handleFieldNameUpdate.bind(this);
  }

  handleFieldNameUpdate(formGroup: FormGroup) {
    if (
      (!formGroup.get('filedName')?.value ||
        formGroup.get('fieldName')?.value ===
          sharedConstants.defaultFieldName ||
        this.valueOptions.includes(this.data.fieldName)) &&
      this.data.value
    ) {
      formGroup.get('fieldName').setValue(this.data.value);
    }
  }
}
