// app/src/pages/integration/common/IntegrationPropertiesMenu.tsx
import React from 'react';
import { Button } from '@mui/material';
import { useAlert } from '@/services/alert/useAlert';

interface IntegrationPropertiesMenuProps {
  onMenuClick: (value: string) => void;
  properties: any;
  isvalidForm: boolean;
  isView?: boolean;
  validateForm?: () => void;
  activeMenuProperties?: string;
}

const IntegrationPropertiesMenu: React.FC<IntegrationPropertiesMenuProps> = ({
  onMenuClick,
  properties,
  isvalidForm,
  isView = false,
  validateForm,
  activeMenuProperties = 'integration_properties'
}) => {
  const { infoAlert } = useAlert();

  const handleMenuClick = (value: string) => {
    if (!isView && !isvalidForm) {
      if (validateForm) {
        validateForm();
      }
      infoAlert('Please fill all required fields.', '');
      return;
    }
    onMenuClick(value);
  };

  return (
    <>
      <div className="integration-button-left-container bg-gray-50 border-b border-gray-300">
        <Button
          className={`btn-properties w-[86%] border border-gray-300 text-gray-700 text-left py-3 px-3.5 rounded m-4 bg-white ${
            activeMenuProperties === 'integration_properties' ? 'button-active border-blue-400 text-blue-700' : ''
          }`}
          onClick={() => handleMenuClick('integration_properties')}
        >
          <span className="material-icons text-sm mr-1">description</span>
          <span className="label-child">Integration Properties</span>
        </Button>
      </div>
      
      <div className="integration-button-left-container list-btn-counter my-3">
        <Button
          className={`btn-properties btn-margin w-[86%] border border-gray-300 text-gray-700 text-left py-3 px-3.5 rounded mx-4 my-1 bg-white ${
            activeMenuProperties === 'input_properties' ? 'button-active border-blue-400 text-blue-700' : ''
          }`}
          onClick={() => handleMenuClick('input_properties')}
          disabled={!properties.partner}
        >
          <span className="material-icons text-sm mr-1">arrow_forward</span>
          <span className="label-child">Input Properties</span>
        </Button>
        
        <Button
          className={`btn-properties btn-margin w-[86%] border border-gray-300 text-gray-700 text-left py-3 px-3.5 rounded mx-4 my-1 bg-white ${
            activeMenuProperties === 'response_properties' ? 'button-active border-blue-400 text-blue-700' : ''
          }`}
          onClick={() => handleMenuClick('response_properties')}
          disabled={!properties.partner}
        >
          <span className="material-icons text-sm mr-1">arrow_back</span>
          <span className="label-child">Response Properties</span>
        </Button>
        
        <Button
          className={`btn-properties btn-margin w-[86%] border border-gray-300 text-gray-700 text-left py-3 px-3.5 rounded mx-4 my-1 bg-white ${
            activeMenuProperties === 'integration_parameters' ? 'button-active border-blue-400 text-blue-700' : ''
          }`}
          onClick={() => handleMenuClick('integration_parameters')}
        >
          <span className="material-icons text-sm mr-1">settings</span>
          <span className="label-child">Integration Parameters</span>
        </Button>
        
        <Button
          className={`btn-properties btn-margin w-[86%] border border-gray-300 text-gray-700 text-left py-3 px-3.5 rounded mx-4 my-1 bg-white ${
            activeMenuProperties === 'scheduling_properties' ? 'button-active border-blue-400 text-blue-700' : ''
          }`}
          onClick={() => handleMenuClick('scheduling_properties')}
        >
          <span className="material-icons text-sm mr-1">schedule</span>
          <span className="label-child">Scheduling</span>
        </Button>
        
        <Button
          className={`btn-properties btn-margin w-[86%] border border-gray-300 text-gray-700 text-left py-3 px-3.5 rounded mx-4 my-1 bg-white ${
            activeMenuProperties === 'alerts_properties' ? 'button-active border-blue-400 text-blue-700' : ''
          }`}
          onClick={() => handleMenuClick('alerts_properties')}
        >
          <span className="material-icons text-sm mr-1">notifications</span>
          <span className="label-child">Alerts</span>
        </Button>
        
        <Button
          className={`btn-properties btn-margin w-[86%] border border-gray-300 text-gray-700 text-left py-3 px-3.5 rounded mx-4 my-1 bg-white ${
            activeMenuProperties === 'dependencies_properties' ? 'button-active border-blue-400 text-blue-700' : ''
          }`}
          onClick={() => handleMenuClick('dependencies_properties')}
        >
          <span className="material-icons text-sm mr-1">device_hub</span>
          <span className="label-child">Dependencies</span>
        </Button>
        
        <Button
          className={`btn-properties btn-margin w-[86%] border border-gray-300 text-gray-700 text-left py-3 px-3.5 rounded mx-4 my-1 bg-white ${
            activeMenuProperties === 'error_code_mapping_properties' ? 'button-active border-blue-400 text-blue-700' : ''
          }`}
          onClick={() => handleMenuClick('error_code_mapping_properties')}
        >
          <span className="material-icons text-sm mr-1">error_outline</span>
          <span className="label-child">Error Code Mapping</span>
        </Button>
      </div>
    </>
  );
};

export default IntegrationPropertiesMenu;

// app/src/integration/common/integration-properties-menu/integration-properties-menu.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { AlertService } from '../../../shared/services/alert.service';

@Component({
  selector: 'app-integration-properties-menu',
  templateUrl: './integration-properties-menu.component.html',
  styleUrls: ['./integration-properties-menu.component.scss'],
})
export class IntegrationPropertiesMenuComponent {
  @Input() onMenuClick: Function;
  @Input() properties;
  @Input() isvalidForm: boolean;
  @Input() isView = false;
  @Output() validateForm: EventEmitter<string> = new EventEmitter<string>();
  activeMenuProperties = 'integration_properties';
  constructor(private alertService: AlertService) {}

  onClickOnMenuSelection(value: string) {
    if (!this.isvalidForm && !this.isView) {
      this.validateForm.emit();
      this.alertService.infoAlert('Please fill all required fields.', '');

      return;
    }
    this.activeMenuProperties = value;
    this.onMenuClick(value);
  }
}

<div class="integration-button-left-container grey-background">
  <button
    mat-button-outline
    class="btn-properties"
    [ngClass]="{ 'button-active': activeMenuProperties === 'integration_properties' }"
    (click)="onClickOnMenuSelection('integration_properties')">
    <mat-icon matPrefix svgIcon="file" class="integratelist-icon"></mat-icon>
    <mat-label class="label-child">Integration Properties</mat-label>
  </button>
</div>
<div class="integration-button-left-container list-btn-counter">
  <button
    mat-button-outline
    class="btn-properties btn-margin"
    [ngClass]="{ 'button-active': activeMenuProperties === 'input_properties' }"
    (click)="onClickOnMenuSelection('input_properties')"
    [disabled]="!properties.partner">
    <mat-icon
      matPrefix
      svgIcon="arrows-right"
      class="integratelist-icon"></mat-icon>
    <mat-label class="label-child">Input Properties</mat-label>
  </button>
  <button
    mat-button-outline
    class="btn-properties btn-margin"
    [ngClass]="{ 'button-active': activeMenuProperties === 'response_properties' }"
    (click)="onClickOnMenuSelection('response_properties')"
    [disabled]="!properties.partner">
    <mat-icon
      matPrefix
      svgIcon="arrows-left"
      class="integratelist-icon"></mat-icon>
    <mat-label class="label-child">Response Properties</mat-label>
  </button>
  <button
    mat-button-outline
    class="btn-properties btn-margin"
    [ngClass]="{ 'button-active': activeMenuProperties === 'integration_parameters' }"
    (click)="onClickOnMenuSelection('integration_parameters')">
    <mat-icon
      matPrefix
      svgIcon="parameters"
      class="integratelist-icon"></mat-icon>
    <mat-label class="label-child">Integration Parameters</mat-label>
  </button>
  <button
    mat-button-outline
    class="btn-properties btn-margin"
    [ngClass]="{ 'button-active': activeMenuProperties === 'scheduling_properties' }"
    (click)="onClickOnMenuSelection('scheduling_properties')">
    <mat-icon
      matPrefix
      svgIcon="clock-refresh"
      class="integratelist-icon"></mat-icon>
    <mat-label class="label-child">Scheduling</mat-label>
  </button>
  <button
    mat-button-outline
    class="btn-properties btn-margin"
    [ngClass]="{ 'button-active': activeMenuProperties === 'alerts_properties' }"
    (click)="onClickOnMenuSelection('alerts_properties')">
    <mat-icon matPrefix svgIcon="bell" class="integratelist-icon"></mat-icon>
    <mat-label class="label-child">Alerts</mat-label>
  </button>
  <button
    mat-button-outline
    class="btn-properties btn-margin"
    [ngClass]="{ 'button-active': activeMenuProperties === 'dependencies_properties' }"
    (click)="onClickOnMenuSelection('dependencies_properties')">
    <mat-icon
      matPrefix
      svgIcon="dependency"
      class="integratelist-icon"></mat-icon>
    <mat-label class="label-child">Dependencies</mat-label>
  </button>
  <button
    mat-button-outline
    class="btn-properties btn-margin"
    [ngClass]="{ 'button-active': activeMenuProperties === 'error_code_mapping_properties' }"
    (click)="onClickOnMenuSelection('error_code_mapping_properties')">
    <mat-icon
      matPrefix
      svgIcon="alert-circle"
      class="integratelist-icon"></mat-icon>
    <mat-label class="label-child">Error Code Mapping</mat-label>
  </button>
</div>
