// app/common-components/execution-log-dialog/execution-log-dialog.component.ts
import { DIALOG_DATA } from '@angular/cdk/dialog';
import {
  AfterViewInit,
  ChangeDetectorRef,
  Component,
  ElementRef,
  Inject,
  OnInit,
  Renderer2,
} from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { saveAs } from 'file-saver';
import { RunhistoriesService } from 'src/app/shared/services/runhistories.service';

@Component({
  selector: 'app-execution-log-dialog',
  templateUrl: './execution-log-dialog.component.html',
  styleUrls: ['./execution-log-dialog.component.scss'],
})
export class ExecutionLogDialogComponent implements OnInit, AfterViewInit {
  integrationId: any;
  runId: any;
  log: any;
  searchTerm = '';
  highlightedLog: SafeHtml = '';
  searchResults: number[] = [];
  currentResultIndex = 0;

  constructor(
    @Inject(DIALOG_DATA) public data: any,
    private runHistoriesService: RunhistoriesService,
    private sanitizer: DomSanitizer,
    private renderer: Renderer2,
    private elementRef: ElementRef,
    private cdr: ChangeDetectorRef,
  ) {}

  ngOnInit() {
    this.integrationId =
      this.data?.integrationId?._id || this.data?.integrationId;
    this.runId = this.data?.runId;
    this.getLogs();
  }

  ngAfterViewInit() {
    this.applyHighlightStyles();
    this.scrollToResult(0);
  }

  getLogs() {
    const params = {
      integrationId: this.integrationId,
      runId: this.runId,
    };

    if (this.integrationId && this.runId) {
      this.runHistoriesService.getLogFile(params).subscribe((res) => {
        if (res && res.body) {
          const uint8Array = new Uint8Array(res.body.data);
          const blob = new Blob([uint8Array], {
            type: `text/log;charset=utf-8`,
          });
          const reader = new FileReader();

          reader.onloadend = () => {
            const content = (reader.result as string) || '';

            this.log = content;
            this.onSearchInputChange();
          };
          reader.readAsText(blob);
        }
      });
    }
  }

  onSearchInputChange() {
    this.searchResults = this.findSearchResults(this.log, this.searchTerm);
    this.currentResultIndex = 0;
    this.updateHighlightedLog();
    this.applyHighlightStyles();
  }

  private findSearchResults(content: string, searchTerm: string): number[] {
    const results: number[] = [];

    if (searchTerm) {
      const regex = new RegExp(searchTerm, 'gi');
      let match;

      while ((match = regex.exec(content)) !== null) {
        results.push(match.index);
      }
    }

    return results;
  }

  private applyHighlightStyles() {
    const style = this.renderer.createElement('style');
    const css = `
      .highlight {
        background-color: yellow;
        font-weight: bold;
      }
      .current-result {
        border: 2px solid red;
        box-shadow: 0 0 10px red;
      }
    `;

    this.renderer.appendChild(style, this.renderer.createText(css));
    this.renderer.appendChild(this.elementRef.nativeElement, style);
  }

  scrollToResult(index: number) {
    const resultContainer = this.elementRef.nativeElement.querySelector(
      `.result-${index}`,
    );

    if (resultContainer) {
      resultContainer.scrollIntoView({ behavior: 'smooth', block: 'center' });
    }
  }

  onSearchInputKeyPress(event: KeyboardEvent) {
    if (event.key === 'Enter') {
      event.preventDefault();
      this.currentResultIndex =
        (this.currentResultIndex + 1) % this.searchResults.length;
      this.updateHighlightedLog();
      this.scrollToResult(this.currentResultIndex);
    }
  }

  private updateHighlightedLog() {
    if (this.searchResults.length > 0) {
      const result = this.searchResults[this.currentResultIndex];
      const match = this.log.substring(result, result + this.searchTerm.length);

      this.highlightedLog = this.sanitizer.bypassSecurityTrustHtml(
        this.highlightMatch(this.log, match, result),
      );
      this.cdr.detectChanges();
    } else {
      this.highlightedLog = this.sanitizer.bypassSecurityTrustHtml(this.log);
    }
  }

  private highlightMatch(
    content: string,
    match: string,
    index: number,
  ): string {
    return this.currentResultIndex > 0
      ? content.substring(0, index) +
          content
            .substring(index)
            .replace(
              match,
              `<span class="highlight result-${this.currentResultIndex}">${match}</span>`,
            )
      : content.replace(
          match,
          `<span class="highlight result-${this.currentResultIndex}">${match}</span>`,
        );
  }

  downloadFile() {
    const params = {
      integrationId: this.integrationId,
      runId: this.runId,
    };

    if (this.integrationId && this.runId) {
      this.runHistoriesService.getLogFile(params).subscribe((res) => {
        if (res && res.body) {
          const uint8Array = new Uint8Array(res.body.data);
          const blob = new Blob([uint8Array], {
            type: `text/log;charset=utf-8`,
          });

          saveAs(blob, `RCX-FX_${this.integrationId}_${this.runId}.log`);
        }
      });
    }
  }
}

// app/src/components/common/ExecutionLogDialog/index.tsx
import React, { useState, useEffect, useRef } from 'react';
import { 
  Dialog, 
  DialogTitle, 
  DialogContent, 
  DialogActions, 
  Button, 
  TextField, 
  IconButton,
  InputAdornment,
  Typography
} from '@mui/material';
import SearchIcon from '@mui/icons-material/Search';
import RefreshIcon from '@mui/icons-material/Refresh';
import DownloadIcon from '@mui/icons-material/Download';
import CloseIcon from '@mui/icons-material/Close';
import { saveAs } from 'file-saver';

interface ExecutionLogDialogProps {
  open: boolean;
  onClose: () => void;
  data: {
    integrationId: string;
    runId: string;
  };
  getLogFile: (params: { integrationId: string; runId: string }) => Promise<any>;
}

const ExecutionLogDialog: React.FC<ExecutionLogDialogProps> = ({ 
  open, 
  onClose, 
  data,
  getLogFile
}) => {
  const [log, setLog] = useState<string>('');
  const [highlightedLog, setHighlightedLog] = useState<string>('');
  const [searchTerm, setSearchTerm] = useState<string>('');
  const [searchResults, setSearchResults] = useState<number[]>([]);
  const [currentResultIndex, setCurrentResultIndex] = useState<number>(0);
  const logContainerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (open && data) {
      getLogs();
    }
  }, [open, data]);

  const getLogs = async () => {
    if (!data?.integrationId || !data?.runId) return;
    
    try {
      const params = {
        integrationId: data.integrationId,
        runId: data.runId
      };
      
      const response = await getLogFile(params);
      
      if (response && response.body) {
        const uint8Array = new Uint8Array(response.body.data);
        const blob = new Blob([uint8Array], { type: 'text/log;charset=utf-8' });
        const reader = new FileReader();
        
        reader.onloadend = () => {
          const content = reader.result as string || '';
          setLog(content);
          onSearchInputChange();
        };
        
        reader.readAsText(blob);
      }
    } catch (error) {
      console.error('Error fetching logs:', error);
    }
  };

  const onSearchInputChange = () => {
    const results = findSearchResults(log, searchTerm);
    setSearchResults(results);
    setCurrentResultIndex(0);
    updateHighlightedLog();
  };

  const findSearchResults = (content: string, searchTerm: string): number[] => {
    const results: number[] = [];
    
    if (searchTerm) {
      const regex = new RegExp(searchTerm, 'gi');
      let match;
      
      while ((match = regex.exec(content)) !== null) {
        results.push(match.index);
      }
    }
    
    return results;
  };

  const updateHighlightedLog = () => {
    if (searchResults.length > 0) {
      const result = searchResults[currentResultIndex];
      const match = log.substring(result, result + searchTerm.length);
      
      setHighlightedLog(highlightMatch(log, match, result));
      
      setTimeout(() => {
        scrollToResult(currentResultIndex);
      }, 100);
    } else {
      setHighlightedLog(log);
    }
  };

  const highlightMatch = (content: string, match: string, index: number): string => {
    return currentResultIndex > 0
      ? content.substring(0, index) +
        content
          .substring(index)
          .replace(
            match,
            `<span class="bg-yellow-300 font-bold result-${currentResultIndex}">${match}</span>`
          )
      : content.replace(
          match,
          `<span class="bg-yellow-300 font-bold result-${currentResultIndex}">${match}</span>`
        );
  };

  const scrollToResult = (index: number) => {
    const resultElement = document.querySelector(`.result-${index}`);
    if (resultElement && logContainerRef.current) {
      resultElement.scrollIntoView({ behavior: 'smooth', block: 'center' });
    }
  };

  const onSearchInputKeyPress = (event: React.KeyboardEvent) => {
    if (event.key === 'Enter') {
      event.preventDefault();
      setCurrentResultIndex((currentResultIndex + 1) % searchResults.length);
      updateHighlightedLog();
    }
  };

  const downloadFile = async () => {
    if (!data?.integrationId || !data?.runId) return;
    
    try {
      const params = {
        integrationId: data.integrationId,
        runId: data.runId
      };
      
      const response = await getLogFile(params);
      
      if (response && response.body) {
        const uint8Array = new Uint8Array(response.body.data);
        const blob = new Blob([uint8Array], { type: 'text/log;charset=utf-8' });
        
        saveAs(blob, `RCX-FX_${data.integrationId}_${data.runId}.log`);
      }
    } catch (error) {
      console.error('Error downloading file:', error);
    }
  };

  return (
    <Dialog 
      open={open} 
      onClose={onClose}
      maxWidth="md"
      fullWidth
    >
      <DialogTitle className="flex justify-between items-center">
        <Typography variant="h6">Execution Log</Typography>
        <IconButton onClick={onClose} size="small">
          <CloseIcon />
        </IconButton>
      </DialogTitle>
      
      <DialogContent>
        <div className="border border-gray-200 rounded-md">
          <div className="flex items-center p-4 border-b border-gray-200">
            <TextField
              fullWidth
              placeholder="Search"
              variant="outlined"
              size="small"
              value={searchTerm}
              onChange={(e) => {
                setSearchTerm(e.target.value);
                onSearchInputChange();
              }}
              onKeyPress={onSearchInputKeyPress}
              InputProps={{
                startAdornment: (
                  <InputAdornment position="start">
                    <SearchIcon />
                  </InputAdornment>
                ),
                endAdornment: searchResults.length > 0 && (
                  <InputAdornment position="end">
                    <span className="text-sm text-gray-500">
                      {currentResultIndex + 1}/{searchResults.length}
                    </span>
                  </InputAdornment>
                ),
              }}
            />
            
            <Button
              variant="outlined"
              className="ml-2"
              onClick={getLogs}
              startIcon={<RefreshIcon />}
            >
              Refresh
            </Button>
          </div>
          
          <div 
            ref={logContainerRef}
            className="bg-gray-50 p-4 h-80 overflow-auto whitespace-pre-wrap"
            dangerouslySetInnerHTML={{ __html: highlightedLog || log || '' }}
          />
        </div>
      </DialogContent>
      
      <DialogActions className="p-4">
        <Button
          variant="outlined"
          startIcon={<DownloadIcon />}
          onClick={downloadFile}
          className="mr-2"
        >
          Download Log
        </Button>
        
        <Button
          variant="contained"
          onClick={onClose}
          className="bg-blue-800 text-white"
        >
          Ok
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default ExecutionLogDialog;
