// app/src/pages/integration/common/DependenciesProperties.tsx
import React, { useState, useEffect } from 'react';
import { 
  TextField, 
  InputAdornment, 
  Button, 
  Typography,
  Dialog
} from '@mui/material';
import SearchIcon from '@mui/icons-material/Search';
import AddIcon from '@mui/icons-material/Add';
import { DynamicTable } from '@/components/common';
import CreateEditDependency from './CreateEditDependency';

interface DependenciesPropertiesProps {
  data: any[];
  handlers: any;
  integrations: any[];
  isView: boolean;
  dataChange: (data: any[]) => void;
}

const DependenciesProperties: React.FC<DependenciesPropertiesProps> = ({ 
  data, 
  handlers, 
  integrations,
  isView,
  dataChange 
}) => {
  const [searchedValue, setSearchedValue] = useState('');
  const [listData, setListData] = useState<any[]>([]);
  const [dataCollection, setDataCollection] = useState<any[]>([]);
  const [config, setConfig] = useState<any>(null);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [selectedRow, setSelectedRow] = useState<any>(null);

  useEffect(() => {
    // In a real implementation, this would fetch from a config service
    setConfig({
      data: [
        { name: 'name', label: 'Dependency Name', type: 'text' },
        { name: 'type', label: 'Dependency Type', type: 'text' },
        { name: 'list', label: 'Integrations', type: 'text' },
        { name: 'actions', label: 'Actions', type: 'actions' }
      ],
      actions: [
        { name: 'Edit', iconname: 'edit', clickHandler: 'edit' },
        { name: 'Delete', iconname: 'delete', clickHandler: 'delete' }
      ]
    });
    
    setInitialData();
  }, [data, integrations]);

  const setInitialData = () => {
    const formattedData = data.map(d => {
      const integrationNames = d.list
        .map((id: string) => {
          const integration = integrations.find(i => i.id === id);
          return integration ? integration.name : null;
        })
        .filter(Boolean);
      
      return { 
        ...d, 
        list: integrationNames 
      };
    });
    
    setListData(formattedData);
    setDataCollection(formattedData);
  };

  const handleSearchInputValueChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const value = event.target.value.toLowerCase();
    setSearchedValue(value);
    
    if (value.length) {
      const filteredData = dataCollection.filter(
        (el) => el.name?.toLowerCase().includes(value)
      );
      setListData(filteredData);
    } else {
      setListData(dataCollection);
    }
  };

  const handleEdit = (row: any) => {
    // Find the original row with IDs instead of names
    const originalRow = { ...row };
    const found = data.find(
      (d) => d.name === row.name && d.type === row.type
    );
    
    if (found && found.list) {
      originalRow.list = [...found.list];
    }
    
    setSelectedRow(originalRow);
    setDialogOpen(true);
  };

  const handleDelete = (row: any, rowNum: number) => {
    const index = data.findIndex((dependency, ind) => {
      if (!dependency.name && !row.name) {
        return ind === rowNum;
      }
      return dependency.name === row.name;
    });

    if (index > -1) {
      const newData = [
        ...data.slice(0, index),
        ...data.slice(index + 1)
      ];
      
      dataChange(newData);
      setInitialData();
    }
  };

  const handleCreate = () => {
    setSelectedRow(null);
    setDialogOpen(true);
  };

  const handleCloseDialog = () => {
    setDialogOpen(false);
  };

  const handleSaveDependency = (dependency: any) => {
    if (selectedRow) {
      // Edit existing dependency
      const newData = data.map((item) =>
        item.name === selectedRow.name ? dependency : item
      );
      dataChange(newData);
    } else {
      // Add new dependency
      const newData = [...data, dependency];
      dataChange(newData);
    }
    
    setDialogOpen(false);
    setInitialData();
  };

  const tableHandlers = {
    edit: handleEdit,
    delete: handleDelete
  };

  return (
    <div className="form">
      <div className="right-panel-header">
        <div className="right-panel-left-content">
          <div className="bread-crum">
            <p className="tproperties">Dependencies</p>
          </div>
        </div>
      </div>
      <div className="right-panel-main-content">
        <div className="dash-tablewrap border border-gray-200 rounded-md">
          <div className="title-wrap flex items-center justify-between p-4 border-b border-gray-200">
            <div>
              <TextField
                variant="outlined"
                size="small"
                placeholder="Search by Dependency Name"
                className="search-box w-[370px]"
                InputProps={{
                  startAdornment: (
                    <InputAdornment position="start">
                      <SearchIcon className="icon-small text-gray-400" />
                    </InputAdornment>
                  ),
                }}
                onChange={handleSearchInputValueChange}
              />
            </div>
            {!isView && (
              <Button
                variant="contained"
                startIcon={<AddIcon className="icon-small" />}
                onClick={handleCreate}
                className="bg-blue-800 hover:bg-blue-900"
              >
                Create New
              </Button>
            )}
          </div>
          <div className="table">
            <div className="responsive-table">
              {config && (
                <DynamicTable
                  config={config}
                  data={listData}
                  handlers={tableHandlers}
                  isView={isView}
                />
              )}
            </div>
          </div>
        </div>
      </div>

      <Dialog 
        open={dialogOpen} 
        onClose={handleCloseDialog}
        maxWidth="md"
        fullWidth
      >
        <CreateEditDependency 
          data={{
            row: selectedRow,
            handlers,
            integrations
          }}
          onClose={handleCloseDialog}
          onSave={handleSaveDependency}
        />
      </Dialog>
    </div>
  );
};

export default DependenciesProperties;

// app/integration/common/dependencies-properties/dependencies-properties.component.ts
import { LiveAnnouncer } from '@angular/cdk/a11y';
import {
  Component,
  EventEmitter,
  Input,
  OnInit,
  Output,
  ViewChild,
} from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { MatSort, Sort } from '@angular/material/sort';
import { UiConfigService } from 'src/app/shared/services/ui-config.service';
import { CreateEditDependencyComponent } from './../create-edit-dependency/create-edit-dependency.component';

@Component({
  selector: 'app-dependencies-properties',
  templateUrl: './dependencies-properties.component.html',
  styleUrls: ['./dependencies-properties.component.scss'],
})
export class DependenciesPropertiesComponent implements OnInit {
  @ViewChild(MatSort) sort: MatSort = new MatSort();
  @Input() data;
  @Input() handlers;
  @Input() integrations;
  @Input() isView;
  @Output() dataChange = new EventEmitter<any>();
  config: any;
  handler: any = {
    edit: this.edit.bind(this),
    delete: this.delete.bind(this),
  };

  listData = [];
  dataCollection: any = [];
  searchedValue: any = '';
  constructor(
    private _liveAnnouncer: LiveAnnouncer,
    public dialog: MatDialog,
    private uiConfigService: UiConfigService,
  ) {}

  async ngOnInit() {
    this.integrations = this.integrations.map((i) => {
      return { name: i.name, id: i._id };
    });
    this.config =
      (await this.uiConfigService.getListViewConfig('dependencies')) || {};
    this.setInitialData();
    this.dataChange.subscribe((data) => {
      this.dataCollection = data;
    });
  }

  setInitialData() {
    const temp = [];

    for (const d of this.data) {
      const list = this.integrations
        .filter((i) => d.list.includes(i.id))
        .map((i) => i.name);

      temp.push({ ...d, list });
    }
    this.listData = temp;
    this.dataCollection = [...this.listData];
  }

  /** Announce the change in sort state for assistive technology. */
  announceSortChange(sortState: Sort) {
    // This example uses English messages. If your application supports
    // multiple language, you would internationalize these strings.
    // Furthermore, you can customize the message to add additional
    // details about the values being sorted.
    if (sortState.direction) {
      this._liveAnnouncer.announce(`Sorted ${sortState.direction}ending`);
    } else {
      this._liveAnnouncer.announce('Sorting cleared');
    }
  }

  openDialog(row, cb) {
    const dialogRef = this.dialog.open(CreateEditDependencyComponent, {
      width: '720px',
      data: {
        row,
        handlers: this.handlers,
        integrations: this.integrations,
      },
    });

    dialogRef.afterClosed().subscribe(cb);
  }

  create() {
    this.openDialog(null, (result) => {
      if (result) {
        const newData = [...this.data, result];

        this.updateData(newData);
      }
    });
  }

  updateData(newData) {
    this.data = newData;
    this.dataChange.emit(this.data);
    this.setInitialData();
  }

  edit(row: any): void {
    row = { ...row };
    const found = this.data.find(
      (d) =>
        d.name === row.name &&
        d.type === row.type &&
        d.list.length === row.list.length,
    );

    if (found && found.list) {
      row.list = [...found.list];
    }
    this.openDialog(row, (result) => {
      if (result) {
        const newData = this.data.map((dependency) =>
          dependency.name === row.name ? result : dependency,
        );

        this.updateData(newData);
      }
    });
  }

  delete(row: any, rowNum: any): void {
    const index = this.data.findIndex((dependency, ind) => {
      if (!dependency.name && !row.name) {
        return ind === rowNum;
      }

      return dependency.name === row.name;
    });

    if (index > -1) {
      const newData = [
        ...this.data.slice(0, index),
        ...this.data.slice(index + 1),
      ];

      this.data = newData;
      this.dataChange.emit(this.data);
      this.setInitialData();
    }
  }

  getClassName(statusParam: string) {
    return `status-${statusParam.toLowerCase()}`;
  }

  getString(input: string) {
    return `${
      input.charAt(0).toUpperCase() + input.slice(1).replace('_', ' ')
    }`;
  }

  transform(value: any) {
    return Array.from(value);
  }

  normalField(item: string) {
    return this.actionField(item)
      ? false
      : this.statusField(item)
        ? false
        : true;
  }

  actionField(item: string) {
    return item === 'actions' ? true : false;
  }

  statusField(item: string) {
    return item === 'status' ? true : false;
  }

  formatLabel(totalMinutes: number): string {
    if (totalMinutes) {
      if (totalMinutes > 60) {
        const hours = Math.floor(totalMinutes / 60);
        const minutes = totalMinutes % 60;

        return `${hours} hr ${minutes} min`;
      } else {
        const fullDuration =
          totalMinutes === 60 ? `${totalMinutes} hr` : `${totalMinutes} min`;

        // this.duration = fullDuration;
        return fullDuration;
      }
    } else {
      return '';
    }
  }

  onSearchInputValueChange(event: any) {
    this.searchedValue = event.target.value;
    this.searchedValue = this.searchedValue.toLowerCase();
    if (this.searchedValue.length) {
      this.data = this.dataCollection.filter(
        (el) => el.name?.toLowerCase().includes(this.searchedValue),
      );
    } else {
      this.data = this.dataCollection;
    }
    this.listData = [...this.data];
  }
}

<div class="form">
  <div class="right-panel-header">
    <div class="right-panel-left-content">
      <div class="bread-crum">
        <p class="tproperties">Dependencies</p>
      </div>
    </div>
  </div>
  <div class="right-panel-main-content">
    <div class="dash-tablewrap">
      <div class="title-wrap">
        <div>
          <mat-form-field appearance="outline" class="search-box width-370">
            <mat-icon
              matPrefix
              svgIcon="magnifier"
              class="icon-small"></mat-icon>
            <input
              matInput
              type="search"
              placeholder="Search by Dependency Name"
              (input)="onSearchInputValueChange($event)" />
          </mat-form-field>
        </div>
        <button
          class="theme-button active-btn"
          mat-flat-button
          color="primary"
          aria-label="Create Alert"
          (click)="create()"
          *ngIf="!isView">
          <mat-icon svgIcon="plus" class="icon-small"></mat-icon>Create New
        </button>
      </div>
      <div class="table">
        <div class="responsive-table">
          <app-dynamic-table
            *ngIf="config"
            [config]="config"
            [data]="listData"
            [handlers]="handler"
            [isView]="isView">
          </app-dynamic-table>
        </div>
      </div>
    </div>
  </div>
</div>
