// app/integration/common/response-properties/response-properties.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { UiConfigService } from 'src/app/shared/services/ui-config.service';

@Component({
  selector: 'app-response-properties',
  templateUrl: './response-properties.component.html',
  styleUrls: ['./response-properties.component.scss'],
})
export class ResponsePropertiesComponent {
  @Input() data;
  @Input() handlers;
  @Input() properties;
  @Output() formStatus: EventEmitter<FormGroup> = new EventEmitter<FormGroup>();
  connections = [];
  config: any;
  requiredData: any = {};

  constructor(private uiConfigService: UiConfigService) {}

  async ngOnInit() {
    // if (this.data.connectionType) {
    this.config =
      (await this.uiConfigService.getFormViewConfig('integrations')) || {};
    this.connections = this.handlers.getConnectionsByParnter();
    this.requiredData.connections = this.connections;
    // }
  }

  onConnectionTypeChange() {
    this.data.connection = '';
    this.connections = this.handlers.getConnectionsByParnter();
  }

  updateFormGroup(formGroup: FormGroup) {
    this.formStatus.emit(formGroup);
    formGroup.valueChanges.subscribe(() => {
      this.handlers.handleIsModifiedChange(true);
    });
  }
}

<div class="form">
  <div class="right-panel-header">
    <div class="right-panel-left-content">
      <div class="bread-crum">
        <p class="tproperties">Response Properties</p>
      </div>
    </div>
  </div>
  <app-dynamic-form
    *ngIf="config"
    [data]="data"
    [handlers]="handlers"
    [config]="config"
    [requiredData]="requiredData"
    [title]="'intResponseProperties'"
    (formStatus)="updateFormGroup($event)">
  </app-dynamic-form>
</div>

// app/src/pages/integration/common/ResponseProperties.tsx
import React, { useState, useEffect } from 'react';
import { DynamicForm } from '@/components/common';

interface ResponsePropertiesProps {
  data: any;
  handlers: any;
  properties: any;
  formStatus?: (formGroup: any) => void;
}

const ResponseProperties: React.FC<ResponsePropertiesProps> = ({ 
  data, 
  handlers, 
  properties,
  formStatus 
}) => {
  const [connections, setConnections] = useState<any[]>([]);
  const [config, setConfig] = useState<any>(null);
  const [requiredData, setRequiredData] = useState<any>({});

  useEffect(() => {
    // In a real implementation, this would fetch from a config service
    const fetchConfig = async () => {
      // Simulating config fetch
      setConfig({
        data: {
          intResponseProperties: {
            dataFields: [
              {
                fields: [
                  {
                    field: 'connectionType',
                    label: 'Connection Type',
                    type: 'select',
                    selectData: 'ConnectionType',
                    selectLabel: 'label',
                    selectValue: 'value',
                    required: true,
                    selectionChange: 'onConnectionTypeChange'
                  },
                  {
                    field: 'connection',
                    label: 'Connection',
                    type: 'select',
                    selectData: 'connections',
                    selectLabel: 'name',
                    selectValue: '_id',
                    required: true
                  },
                  {
                    field: 'path',
                    label: 'Path',
                    type: 'text',
                    required: true
                  },
                  {
                    field: 'archivePath',
                    label: 'Archive Path',
                    type: 'text'
                  },
                  {
                    field: 'filePattern',
                    label: 'File Pattern',
                    type: 'text',
                    required: true
                  }
                ]
              }
            ]
          }
        }
      });
    };
    
    fetchConfig();
    
    // Get connections by partner
    setConnections(handlers.getConnectionsByParnter());
    setRequiredData({ connections: handlers.getConnectionsByParnter() });
  }, [handlers]);

  const onConnectionTypeChange = () => {
    if (data) {
      data.connection = '';
      const updatedConnections = handlers.getConnectionsByParnter();
      setConnections(updatedConnections);
      setRequiredData(prev => ({ ...prev, connections: updatedConnections }));
    }
  };

  const updateFormGroup = (formGroup: any) => {
    if (formStatus) {
      formStatus(formGroup);
    }
    
    // Subscribe to form changes
    if (formGroup.valueChanges && formGroup.valueChanges.subscribe) {
      formGroup.valueChanges.subscribe(() => {
        if (handlers.handleIsModifiedChange) {
          handlers.handleIsModifiedChange(true);
        }
      });
    }
  };

  return (
    <div className="form">
      <div className="right-panel-header border-b border-gray-200 py-4 px-8">
        <div className="right-panel-left-content">
          <div className="bread-crum text-base font-semibold text-gray-900">
            <p className="tproperties">Response Properties</p>
          </div>
        </div>
      </div>
      
      {config && (
        <DynamicForm
          config={config}
          data={data}
          handlers={{
            ...handlers,
            onConnectionTypeChange
          }}
          requiredData={requiredData}
          title="intResponseProperties"
          formStatus={updateFormGroup}
        />
      )}
    </div>
  );
};

export default ResponseProperties;
