// app/templates/common/input-file-properties/input-file-properties.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { UiConfigService } from 'src/app/shared/services/ui-config.service';

@Component({
  selector: 'app-input-file-properties',
  templateUrl: './input-file-properties.component.html',
  styleUrls: ['./input-file-properties.component.scss'],
})
export class InputFilePropertiesComponent {
  @Input() data;
  @Input() isView = false;
  @Input() activeFieldDetails;
  @Input() handlers;
  @Input() properties;
  config: any;
  @Output() formStatus: EventEmitter<FormGroup> = new EventEmitter<FormGroup>();

  constructor(private uiConfigService: UiConfigService) {}

  async ngOnInit() {
    this.config =
      (await this.uiConfigService.getFormViewConfig('templates')) || {};
  }

  ngOnChanges() {
    this.data = this.data || {};
  }

  updateFormGroup(formGroup: FormGroup) {
    this.formStatus.emit(formGroup);
    formGroup.valueChanges.subscribe(() => {
      this.handlers.handleIsModifiedChange(true);
    });
  }
}

<div class="form">
  <app-dynamic-form
    *ngIf="config"
    [data]="data"
    [config]="config"
    [properties]="properties"
    [activeFieldDetails]="activeFieldDetails"
    [title]="'inputFileProperties'"
    (formStatus)="updateFormGroup($event)">
  </app-dynamic-form>
</div>

// app/src/pages/Templates/InputFilePropertiesComponent.tsx
import React, { useState, useEffect } from 'react';
import DynamicForm from './DynamicForm';
import { useUiConfig } from '@/services/ui-config/useUiConfig';
import './InputFilePropertiesComponent.css';

interface Props {
  data: any;
  isView: boolean;
  activeFieldDetails: any;
  handlers: any;
  properties: any;
}

const InputFilePropertiesComponent: React.FC<Props> = ({
  data,
  isView,
  activeFieldDetails,
  handlers,
  properties,
}) => {
  const [config, setConfig] = useState({});
  const [formGroup, setFormGroup] = useState(null);

  const { getFormViewConfig } = useUiConfig();

  useEffect(() => {
    const fetchConfig = async () => {
      const configData = await getFormViewConfig('templates');
      setConfig(configData || {});
    };
    fetchConfig();
  }, []);

  const updateFormGroup = (formGroup: any) => {
    setFormGroup(formGroup);
    if (formGroup) {
      formGroup.addEventListener('change', () => {
        handlers.handleIsModifiedChange(true);
      });
    }
  };

  return (
    <div className="form">
      {config && (
        <DynamicForm
          data={data}
          config={config}
          properties={properties}
          activeFieldDetails={activeFieldDetails}
          title="inputFileProperties"
          formStatus={(formGroup: any) => updateFormGroup(formGroup)}
        />
      )}
    </div>
  );
};

export default InputFilePropertiesComponent;
