// app/templates/common/input-header-properties/input-header-properties.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { UiConfigService } from 'src/app/shared/services/ui-config.service';

@Component({
  selector: 'app-input-header-properties',
  templateUrl: './input-header-properties.component.html',
  styleUrls: ['./input-header-properties.component.scss'],
})
export class InputHeaderPropertiesComponent {
  @Input() properties;
  @Input() activeFieldDetails;
  @Input() data;
  @Input() enumData;
  @Input() handlers;
  config: any;
  @Output() formStatus: EventEmitter<FormGroup> = new EventEmitter<FormGroup>();

  constructor(private uiConfigService: UiConfigService) {}

  async ngOnInit() {
    this.config =
      (await this.uiConfigService.getFormViewConfig('templates')) || {};
  }

  ngOnChanges() {
    this.data = this.data || {};
    this.enumData = this.enumData || {};
    this.enumData.DataType = this.enumData.DataType || [];
  }

  updateFormGroup(formGroup: FormGroup) {
    this.formStatus.emit(formGroup);
    formGroup.valueChanges.subscribe(() => {
      this.handlers.handleIsModifiedChange(true);
    });
  }
}

<div class="form">
  <app-dynamic-form
    *ngIf="config"
    [data]="data"
    [handlers]="handlers"
    [properties]="properties"
    [activeFieldDetails]="activeFieldDetails"
    [requiredData]="enumData"
    [config]="config"
    [title]="'inputHeaderProperties'"
    (formStatus)="updateFormGroup($event)">
  </app-dynamic-form>
</div>

// app/src/pages/Templates/InputHeaderProperties.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { useForm } from 'react-hook-form';
import { useUiConfig } from '@/services/ui-config/useUiConfig';
import AppDynamicForm from './app-dynamic-form';

interface InputHeaderPropertiesProps {
  properties: any;
  activeFieldDetails: any;
  data: any;
  enumData: any;
  handlers: any;
}

const InputHeaderProperties = (props: InputHeaderPropertiesProps) => {
  const [config, setConfig] = useState(null);
  const uiConfigService = useUiConfig();

  const updateFormGroup = useCallback((data: any) => {
    props.handlers.handleIsModifiedChange(true);
  }, [props.handlers]);

  useEffect(() => {
    const getConfig = async () => {
      const config = await uiConfigService.getFormViewConfig('templates');
      setConfig(config || {});
    };
    getConfig();
  }, []);

  useEffect(() => {
    props.data = props.data || {};
    props.enumData = props.enumData || {};
    props.enumData.DataType = props.enumData.DataType || [];
  }, [props.data, props.enumData]);

  const { register, handleSubmit } = useForm();

  const onSubmit = (data: any) => {
    updateFormGroup(data);
  };

  return (
    <div className="form">
      {config && (
        <AppDynamicForm
          data={props.data}
          handlers={props.handlers}
          properties={props.properties}
          activeFieldDetails={props.activeFieldDetails}
          requiredData={props.enumData}
          config={config}
          title="inputHeaderProperties"
          onSubmit={onSubmit}
          register={register}
        />
      )}
    </div>
  );
};

export default InputHeaderProperties;
