// app/src/templates/common/response-header-properties/response-header-properties.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { sharedConstants } from 'src/app/shared';
import { UiConfigService } from 'src/app/shared/services/ui-config.service';

@Component({
  selector: 'app-response-header-properties',
  templateUrl: './response-header-properties.component.html',
  styleUrls: ['./response-header-properties.component.scss'],
})
export class ResponseHeaderPropertiesComponent {
  options = ['String', 'Number'];

  @Input() properties;
  @Input() activeFieldDetails;
  @Input() data;
  @Input() enumData;
  @Input() handlers;
  @Input() valueFields;
  @Output() formStatus: EventEmitter<FormGroup> = new EventEmitter<FormGroup>();
  valueOptions = [];
  config: any;

  constructor(private uiConfigService: UiConfigService) {}

  async ngOnInit() {
    this.config =
      (await this.uiConfigService.getFormViewConfig('templates')) || {};
    this.addHandler();
  }

  ngOnChanges() {
    this.data = this.data || {};
    this.enumData = this.enumData || {};
    this.enumData.MathFuncs = this.enumData.MathFuncs || [];
    this.enumData.DataType = this.enumData.DataType || [];
    this.getValues();
  }

  getValues() {
    const values = ['Error Code', 'Error Message', 'HTTP Status', 'Constant', 'Row Number'];
    if (this.properties.rcxProcess === 'Activity') {
      values.push('ActivityId')
    }
    this.valueOptions = values;
    this.enumData.valueOptions = this.valueOptions || [];
  }

  updateFormGroup(formGroup: FormGroup) {
    this.formStatus.emit(formGroup);
    formGroup.valueChanges.subscribe(() => {
      this.handlers.handleIsModifiedChange(true);
    });
  }

  addHandler() {
    this.handlers.handleFieldNameUpdate = this.handleFieldNameUpdate.bind(this);
  }

  handleFieldNameUpdate(formGroup: FormGroup) {
    if (
      (!formGroup.get('filedName')?.value ||
        formGroup.get('fieldName')?.value ===
          sharedConstants.defaultFieldName ||
        this.valueOptions.includes(this.data.fieldName)) &&
      this.data.value
    ) {
      formGroup.get('fieldName').setValue(this.data.value);
    }
  }
}

<div class="form">
  <app-dynamic-form
    *ngIf="config"
    [data]="data"
    [handlers]="handlers"
    [properties]="properties"
    [activeFieldDetails]="activeFieldDetails"
    [requiredData]="enumData"
    [config]="config"
    [title]="'responseHeaderProperties'"
    (formStatus)="updateFormGroup($event)">
  </app-dynamic-form>
</div>

// app/src/pages/Templates/ResponseHeaderPropertiesComponent.tsx
import React, { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { useUiConfig } from '@/services/ui-config/useUiConfig';
import DynamicForm from './DynamicForm';
import './response-header-properties.css';

const options = ['String', 'Number'];
const sharedConstants = {
    defaultFieldName: 'default-field-name',
};

const ResponseHeaderPropertiesComponent = ({
    properties,
    activeFieldDetails,
    data,
    enumData,
    valueFields,
    handlers,
}) => {
    const { getFormViewConfig } = useUiConfig();
    const [config, setConfig] = useState({});
    const [valueOptions, setValueOptions] = useState<any>([]);
    const { register, watch, setValue, formState } = useForm({
        defaultValues: {
            fieldName: '',
        },
    });

    useEffect(() => {
        const fetchConfig = async () => {
            const configData = await getFormViewConfig('templates');
            setConfig(configData || {});
        };
        fetchConfig();
    }, [getFormViewConfig]);

    useEffect(() => {
        const values = [
            'Error Code',
            'Error Message',
            'HTTP Status',
            'Constant',
            'Row Number',
        ];
        if (properties.rcxProcess === 'Activity') {
            values.push('ActivityId');
        }
        setValueOptions(values);
        enumData.valueOptions = valueOptions || [];
    }, [properties, enumData]);

    const handleFieldNameUpdate = (data: any) => {
        if (
            (!data.fieldName ||
                data.fieldName === sharedConstants.defaultFieldName ||
                valueOptions.includes(data.fieldName)) &&
            data.value
        ) {
            setValue('fieldName', data.value);
        }
    };

    const updateFormGroup = (data:any) => {
        handlers.handleIsModifiedChange(true);
    };

    useEffect(() => {
        handlers.handleFieldNameUpdate = handleFieldNameUpdate;
    }, [handlers]);

    return (
        <div className="form">
            {config && (
                <DynamicForm
                    data={data}
                    handlers={{
                        ...handlers,
                        handleFieldNameUpdate,
                    }}
                    properties={properties}
                    activeFieldDetails={activeFieldDetails}
                    requiredData={enumData}
                    config={config}
                    title="responseHeaderProperties"
                    register={register}
                    watch={watch}
                    setValue={setValue}
                    formState={formState}
                    updateFormGroup={updateFormGroup}
                />
            )}
        </div>
    );
};

export default ResponseHeaderPropertiesComponent;
