// app/src/templates/common/template-properties/template-properties.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { UiConfigService } from 'src/app/shared/services/ui-config.service';

@Component({
  selector: 'app-template-properties',
  templateUrl: './template-properties.component.html',
  styleUrls: ['./template-properties.component.scss'],
})
export class TemplatePropertiesComponent {
  @Input() properties;
  @Input() partners;
  @Input() enumData;
  @Input() handlers;
  @Output() formStatus: EventEmitter<FormGroup> = new EventEmitter<FormGroup>();
  options = ['String', 'Number'];
  filteredPartners = [];
  config: any;
  formGroup: FormGroup = new FormGroup([]);

  constructor(private uiConfigService: UiConfigService) {}

  async ngOnInit() {
    // this.filteredPartners = this.partners || [];
    this.config =
      (await this.uiConfigService.getFormViewConfig('templates')) || {};
    this.properties = this.properties || {};
    if (this.properties?.partner) {
      this.properties.partner =
        this.properties.partner?._id || this.properties.partner;
    }
  }

  updateFormGroup(formGroup: FormGroup) {
    this.formGroup = formGroup;
    this.formGroup.controls['partnerFormControl']?.valueChanges.subscribe(
      (searchTerm) => {
        this.enumData.partners = this.filterPartners(searchTerm);
      },
    );
    this.enumData.partnerFormControl =
      this.formGroup.controls['partnerFormControl'];
    this.formStatus.emit(formGroup);
    this.formGroup.valueChanges.subscribe(() => {
      this.handlers.handleIsModifiedChange(true);
    });
  }

  ngOnChanges() {
    this.enumData.partners = this.partners || [];
  }

  filterPartners(searchTerm: string) {
    return this.partners.filter((partner) =>
      partner.name.toLowerCase().includes(searchTerm.toLowerCase()),
    );
    // this.enumData.Partner = this.partners || [];
  }

  resetRCXFields() {
    (
      ((this.properties || {}).inputFileLayout || {}).bodyFieldDefs || []
    ).forEach((def) => {
      def.rcxField = '';
    });
  }
}

<div class="form">
  <app-dynamic-form
    *ngIf="config"
    [requiredData]="enumData"
    [properties]="properties"
    [data]="properties"
    [config]="config"
    [title]="'templateProperties'"
    (formStatus)="updateFormGroup($event)">
  </app-dynamic-form>
</div>

// app/src/pages/Templates/TemplateProperties.tsx
import React, { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { useUiConfig } from '@/services/ui-config/useUiConfig';
import DynamicForm from './DynamicForm'; // Assuming DynamicForm is available

const TemplateProperties = () => {
    const [properties, setProperties] = useState<any>({});
    const [partners, setPartners] = useState([]);
    const [enumData, setEnumData] = useState({});
    const [config, setConfig] = useState({});
    const [formGroup, setFormGroup] = useState(null);
    const [filteredPartners, setFilteredPartners] = useState([]);
    const { getFormViewConfig } = useUiConfig();

    const {
        register,
        watch,
        setValue,
        handleSubmit,
        getValues,
    } = useForm();

    useEffect(() => {
        const fetchConfig = async () => {
            const templateConfig = await getFormViewConfig('templates');
            setConfig(templateConfig || {});
        };
        fetchConfig();
    }, [getFormViewConfig]);

    useEffect(() => {
        if (properties?.partner) {
            setProperties({
                ...properties,
                partner: properties.partner._id || properties.partner,
            });
        }
    }, [properties]);

    const updateFormGroup = (formGroup: any) => {
        setFormGroup(formGroup);
        const searchTerm = watch('partnerFormControl');
        if (searchTerm) {
            const filtered = partners.filter((partner: any) =>
                partner.name.toLowerCase().includes(searchTerm.toLowerCase()),
            );
            setEnumData((prevEnumData) => ({
                ...prevEnumData,
                partners: filtered,
            }));
        }
    };

    const handleChanges = () => {
        // Assuming handlers.handleIsModifiedChange is available
        // If not, please define or replace with desired functionality
        // handlers.handleIsModifiedChange(true);
    };

    const filterPartners = (searchTerm: any) => {
        const filtered = partners.filter((partner: any) =>
            partner.name.toLowerCase().includes(searchTerm.toLowerCase()),
        );
        return filtered;
    };

    const resetRCXFields = () => {
        if (properties.inputFileLayout && properties.inputFileLayout.bodyFieldDefs) {
            properties.inputFileLayout.bodyFieldDefs.forEach((def:any) => {
                def.rcxField = '';
            });
        }
    };

    return (
        <div className="form">
            {config && (
                <DynamicForm
                    register={register}
                    watch={watch}
                    handleSubmit={handleSubmit}
                    setValue={setValue}
                    getValues={getValues}
                    requiredData={enumData}
                    properties={properties}
                    data={properties}
                    config={config}
                    title={'templateProperties'}
                    formStatus={updateFormGroup}
                    onChanges={handleChanges}
                />
            )}
        </div>
    );
};

export default TemplateProperties;
