// app/src/pages/Templates/ResponseFooterPropertiesComponent.tsx
// ResponseFooterPropertiesComponent.tsx
import React, { useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { useUiConfig } from '@/services/ui-config/useUiConfig';
import DynamicForm from './DynamicForm';
import './ResponseFooterPropertiesComponent.css';

interface ResponseFooterPropertiesProps {
  properties: any;
  activeFieldDetails: any;
  data: any;
  enumData: any;
  handlers: any;
  valueFields: any;
}

const ResponseFooterPropertiesComponent: React.FC<ResponseFooterPropertiesProps> = ({
  properties,
  activeFieldDetails,
  data,
  enumData,
  handlers,
  valueFields,
}) => {
  const { config } = useUiConfig('templates');
  const {
    register,
    handleSubmit,
    watch,
    formState: { isDirty },
  } = useForm();

  const [valueOptions, setValueOptions] = React.useState<any>([]);

  useEffect(() => {
    const values = ['Error Code', 'Error Message', 'HTTP Status', 'Constant', 'Row Number'];
    if (properties.rcxProcess === 'Activity') {
      values.push('ActivityId');
    }
    setValueOptions(values);
    enumData.valueOptions = valueOptions;
  }, [properties, enumData, valueOptions]);

  const handleFieldNameUpdate = (formGroup: any) => {
    if (
      (!formGroup.get('filedName')?.value ||
        formGroup.get('fieldName')?.value ===
          'defaultFieldName' ||
        valueOptions.includes(data?.fieldName)) &&
      data.value
    ) {
      formGroup.get('fieldName').setValue(data.value);
    }
  };

  const updateFormGroup = (formGroup: any) => {
    handlers.handleIsModifiedChange(true);
  };

  const addHandler = () => {
    handlers.handleFieldNameUpdate = handleFieldNameUpdate;
  };

  React.useEffect(() => {
    addHandler();
  }, [handlers]);

  if (!config) return null;

  return (
    <div className="form">
      <DynamicForm
        data={data}
        properties={properties}
        activeFieldDetails={activeFieldDetails}
        requiredData={enumData}
        config={config}
        title="responseFooterProperties"
        handlers={handlers}
        formStatus={updateFormGroup}
      />
    </div>
  );
};

export default ResponseFooterPropertiesComponent;

// app/templates/common/response-footer-properties/response-footer-properties.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { sharedConstants } from 'src/app/shared';
import { UiConfigService } from 'src/app/shared/services/ui-config.service';

@Component({
  selector: 'app-response-footer-properties',
  templateUrl: './response-footer-properties.component.html',
  styleUrls: ['./response-footer-properties.component.scss'],
})
export class ResponseFooterPropertiesComponent {
  @Input() properties;
  @Input() activeFieldDetails;
  @Input() data;
  @Input() enumData;
  @Input() handlers;
  @Input() valueFields;
  @Output() formStatus: EventEmitter<FormGroup> = new EventEmitter<FormGroup>();
  valueOptions = [];
  config: any;

  constructor(private uiConfigService: UiConfigService) {}

  async ngOnInit() {
    this.config =
      (await this.uiConfigService.getFormViewConfig('templates')) || {};
    this.addHandler();
  }

  ngOnChanges() {
    this.data = this.data || {};
    this.enumData = this.enumData || {};
    this.enumData.MathFuncs = this.enumData.MathFuncs || [];
    this.enumData.DataType = this.enumData.DataType || [];
    this.getValues();
  }

  getValues() {
    const values = ['Error Code', 'Error Message', 'HTTP Status', 'Constant', 'Row Number'];
    if (this.properties.rcxProcess === 'Activity') {
      values.push('ActivityId')
    }
    this.valueOptions = values;
    this.enumData.valueOptions = this.valueOptions || [];
  }

  updateFormGroup(formGroup: FormGroup) {
    this.formStatus.emit(formGroup);
    formGroup.valueChanges.subscribe(() => {
      this.handlers.handleIsModifiedChange(true);
    });
  }

  addHandler() {
    this.handlers.handleFieldNameUpdate = this.handleFieldNameUpdate.bind(this);
  }

  handleFieldNameUpdate(formGroup: FormGroup) {
    if (
      (!formGroup.get('filedName')?.value ||
        formGroup.get('fieldName')?.value ===
          sharedConstants.defaultFieldName ||
        this.valueOptions.includes(this.data.fieldName)) &&
      this.data.value
    ) {
      formGroup.get('fieldName').setValue(this.data.value);
    }
  }
}

<div class="form">
  <app-dynamic-form
    *ngIf="config"
    [data]="data"
    [properties]="properties"
    [activeFieldDetails]="activeFieldDetails"
    [requiredData]="enumData"
    [config]="config"
    [title]="'responseFooterProperties'"
    [handlers]="handlers"
    (formStatus)="updateFormGroup($event)">
  </app-dynamic-form>
</div>
